// Plan builder for the UI prototype. Uses the same fixed snapshot as the report examples.
const analysisSnapshot=new Date(Date.UTC(2026,8,6,10,40));
const planFrequencyNames={daily:'每天',weekly:'每周',half:'每半月',monthly:'每月',quarterly:'每季度',yearly:'每年',interval:'自定义间隔'};
const planRangeNames={previousDay:'上一个自然日',previousWeek:'上一个自然周',previousHalf:'上一个自然半月',previousMonth:'上一个自然月',previousQuarter:'上一个自然季度',previousYear:'上一个自然年',rolling:'最近 N 天'};
const planDefaults={daily:{frequency:'daily',range:'previousDay'},weekly:{frequency:'weekly',range:'previousWeek'},half:{frequency:'half',range:'previousHalf'},monthly:{frequency:'monthly',range:'previousMonth'},quarterly:{frequency:'quarterly',range:'previousQuarter'},yearly:{frequency:'yearly',range:'previousYear'}};
Object.assign(analysisSchedules,{quarterly:{name:'季报',enabled:true},yearly:{name:'年报',enabled:true}});

Object.assign(autoReports,{quarterly:{title:'2026 年第三季度 · 运营分析',range:'请求周期：2026.07.01 — 09.30；已有数据：08.28 — 09.06 10:40',source:'阶段预览 · 季度尚未结束',coverage:'仅有 10 天记录',description:'季报关注跨月的服务效率、重复问题与资源安排。目前只有 10 天演示数据，不足以判断整个季度的表现。',metrics:[['已有新单','174','单'],['已有闭环','137','单'],['已有数据天数','10','天']],advice:[],emptyTitle:'季度数据不足，暂不形成调配建议',emptyReason:'缺少本季度的大部分记录及完整对照季度。可先查看已有数据，后续再评估持续变化。'},yearly:{title:'2026 年 · 年度运营分析',range:'请求周期：2026.01.01 — 12.31；已有数据：08.28 — 09.06 10:40',source:'阶段预览 · 2027-01-01 生成完整年报',coverage:'仅有 10 / 365 天记录',description:'年报回顾全年工单结构、季节变化、服务效率和建议落实情况，为下一年的人员及运营安排提供依据。现有数据无法代表全年。',metrics:[['已有新单','174','单'],['已有闭环','137','单'],['已有数据天数','10','天']],advice:[],emptyTitle:'全年与同比数据不足',emptyReason:'当前仅有 8月28日至9月6日的演示记录，且没有上一年数据。不会将局部样本外推成年报结论。'}});
let planSequence=0,adHocReport=null;
const planPad=n=>String(n).padStart(2,'0');
const planDate=d=>`${d.getUTCFullYear()}-${planPad(d.getUTCMonth()+1)}-${planPad(d.getUTCDate())}`;
function planCandidate(year,month,day,time){const [h,m]=time.split(':').map(Number),last=new Date(Date.UTC(year,month+1,0)).getUTCDate();return new Date(Date.UTC(year,month,Math.min(day,last),h,m));}
function nextPlanRun(s){const now=analysisSnapshot,y=now.getUTCFullYear(),m=now.getUTCMonth(),day=now.getUTCDate();if(s.frequency==='daily'||s.frequency==='weekly'||s.frequency==='half'){for(let n=0;n<40;n++){let d=planCandidate(y,m,day,s.time);d.setUTCDate(d.getUTCDate()+n);if(d<=now)continue;if(s.frequency==='daily'||s.frequency==='weekly'&&d.getUTCDay()===s.weekday||s.frequency==='half'&&[1,16].includes(d.getUTCDate()))return d;}}
if(['monthly','quarterly','yearly'].includes(s.frequency)){for(let n=0;n<25;n++){const month=m+n,year=y+Math.floor(month/12),monthIndex=month%12;if(s.frequency==='quarterly'&&monthIndex%3!==0)continue;if(s.frequency==='yearly'&&monthIndex!==s.yearMonth-1)continue;const d=planCandidate(year,monthIndex,s.monthDay,s.time);if(d>now)return d;}}
if(s.frequency==='interval'){const [ay,am,ad]=s.anchor.split('-').map(Number);for(let n=0;n<1000;n++){let d;if(s.unit==='months'||s.unit==='years'){const months=(am-1)+n*s.every*(s.unit==='years'?12:1);d=planCandidate(ay+Math.floor(months/12),months%12,ad,s.time);}else{d=planCandidate(ay,am-1,ad,s.time);d.setUTCDate(d.getUTCDate()+n*s.every*(s.unit==='weeks'?7:1));}if(d>now)return d;}}return null;}
function refreshPlanSummary(s){const weekdays=['日','一','二','三','四','五','六'],units={days:'天',weeks:'周',months:'个月',years:'年'};const cadence=s.frequency==='weekly'?`每周${weekdays[s.weekday]}`:s.frequency==='half'?'每月 1、16 日':s.frequency==='monthly'?`每月 ${s.monthDay} 日`:s.frequency==='quarterly'?`每季首月 ${s.monthDay} 日`:s.frequency==='yearly'?`每年 ${s.yearMonth} 月 ${s.monthDay} 日`:s.frequency==='interval'?`每 ${s.every} ${units[s.unit]}`:'每天';s.cadence=`${cadence} ${s.time}`;s.focus=s.range==='rolling'?`分析最近 ${s.rangeDays} 天`:`分析${planRangeNames[s.range]}`;const next=nextPlanRun(s);s.next=next?`${planDate(next)} ${s.time}`:'待设置';}
function showAnalysisSchedule(){modal('自动分析设置',`<p>选择预设周期，或创建自己的分析计划。生成频率和分析范围可以分别设置。</p><div class="plan-manager">${Object.entries(analysisSchedules).map(([key,s])=>`<div class="plan-manager-row"><label class="plan-enable"><input type="checkbox" data-plan-enable="${key}" aria-label="启用${esc(s.name)}" ${s.enabled?'checked':''}><span><strong>${esc(s.name)}</strong><small>${esc(s.cadence)} · ${esc(s.focus)}</small></span></label><button class="text-link" data-plan-edit="${key}">编辑 ${icon('arrow')}</button></div>`).join('')}</div><button class="button plan-add" data-plan-add>${icon('plus')}新增自定义计划</button><div class="modal-summary">例如：每 10 天的 09:00，分析最近 30 天的工单。<br>也可以每年 1 月 1 日生成上一年的年度报告。<br>UTC+8 · 默认仅站内报告 · 当前为设计预览</div>`,'完成设置（演示）',m=>{capturePlanToggles(m);m.close();render();toast('预览计划已保存；未创建真实定时任务');});document.getElementById('modal').classList.add('plan-dialog');}
function capturePlanToggles(m){m.querySelectorAll('[data-plan-enable]').forEach(el=>analysisSchedules[el.dataset.planEnable].enabled=el.checked);}
function planFormOptions(values,selected){return Object.entries(values).map(([k,v])=>`<option value="${k}" ${String(selected)===k?'selected':''}>${esc(v)}</option>`).join('');}
function planFrequencyFields(s){return `${s.frequency==='weekly'?`<label>星期<select id="plan-weekday">${planFormOptions({1:'星期一',2:'星期二',3:'星期三',4:'星期四',5:'星期五',6:'星期六',0:'星期日'},s.weekday)}</select></label>`:''}${['monthly','quarterly','yearly'].includes(s.frequency)?`${s.frequency==='yearly'?`<label>月份<select id="plan-month">${planFormOptions(Object.fromEntries(Array.from({length:12},(_,i)=>[i+1,`${i+1} 月`])),s.yearMonth)}</select></label>`:''}<label>${s.frequency==='quarterly'?'季度首月的日期':'日期'}<input id="plan-day" type="number" min="1" max="31" value="${s.monthDay}"></label>`:''}${s.frequency==='interval'?`<label>每隔<input id="plan-every" type="number" min="1" max="365" value="${s.every}"></label><label>时间单位<select id="plan-unit">${planFormOptions({days:'天',weeks:'周',months:'个月',years:'年'},s.unit)}</select></label><label class="plan-wide">首次生成日期<input id="plan-anchor" type="date" min="2026-01-01" max="2100-12-31" value="${s.anchor}"></label>`:''}<label>生成时间<input id="plan-time" type="time" value="${s.time}" required></label>`;}
let editingPlanKey=null,editingPlanDraft=null;
function editAnalysisPlan(key){editingPlanKey=key;editingPlanDraft=key?{...analysisSchedules[key]}:{name:'自定义运营分析',frequency:'interval',enabled:true,time:'09:00',weekday:1,monthDay:1,yearMonth:1,every:10,unit:'days',anchor:'2026-09-07',range:'rolling',rangeDays:30};renderPlanEditor();}
function readPlanDraft(m){const s=editingPlanDraft,get=(id,old)=>m.querySelector('#'+id)?.value??old;Object.assign(s,{name:get('plan-name',s.name),frequency:get('plan-frequency',s.frequency),time:get('plan-time',s.time),weekday:Number(get('plan-weekday',s.weekday)),monthDay:Number(get('plan-day',s.monthDay)),yearMonth:Number(get('plan-month',s.yearMonth)),every:Number(get('plan-every',s.every)),unit:get('plan-unit',s.unit),anchor:get('plan-anchor',s.anchor),range:get('plan-range',s.range),rangeDays:Number(get('plan-range-days',s.rangeDays))});return s;}
function renderPlanEditor(){const s=editingPlanDraft;modal(editingPlanKey?'编辑分析计划':'新增自定义计划',`<p>决定什么时候生成，以及每次回顾哪些数据。</p><div class="plan-editor"><label class="plan-wide">计划名称<input id="plan-name" maxlength="24" value="${esc(s.name)}" required></label><div class="plan-section-label">01 / 生成安排</div><label>生成频率<select id="plan-frequency">${planFormOptions(planFrequencyNames,s.frequency)}</select></label>${planFrequencyFields(s)}<div class="plan-section-label">02 / 分析范围</div><label class="${s.range==='rolling'?'':'plan-wide'}">每次分析<select id="plan-range">${planFormOptions(planRangeNames,s.range)}</select></label>${s.range==='rolling'?`<label>最近多少天<input id="plan-range-days" type="number" min="1" max="3660" value="${s.rangeDays}"></label>`:''}</div><p class="plan-hint">自然周期只包含已结束的完整周期；最近 N 天截止到生成前一天。月末不足所选日期时，在该月最后一天生成。</p><div class="modal-summary" id="plan-preview"></div>`,'预览并保存',m=>{const v=readPlanDraft(m);if(!validPlan(v,m))return;refreshPlanSummary(v);m.close();modal('确认分析计划',`<div class="modal-summary"><strong>${esc(v.name)}</strong><br>生成安排：${esc(v.cadence)}<br>分析范围：${esc(v.focus)}<br>下次计划：${esc(v.next)}<br>时区：UTC+8</div><p>基于 2026-09-06 10:40 演示时点预览。当前只保存界面配置，不会启动真实后台任务。</p>`,'保存计划（演示）',m2=>{const key=editingPlanKey||`custom${++planSequence}`;analysisSchedules[key]={...v};m2.close();reportCycle=key;reportArchive='latest';render();toast('分析计划已保存到当前预览');});});document.getElementById('modal').classList.add('plan-dialog');updatePlanPreview();}
function validPlan(s,m){for(const el of m.querySelectorAll('input'))if(!el.checkValidity()){el.reportValidity();return false;}if(!s.name.trim()||!s.time||(s.frequency==='interval'&&(!Number.isInteger(s.every)||s.every<1||s.every>365))||(s.range==='rolling'&&(!Number.isInteger(s.rangeDays)||s.rangeDays<1||s.rangeDays>3660))||(['monthly','quarterly','yearly'].includes(s.frequency)&&(!Number.isInteger(s.monthDay)||s.monthDay<1||s.monthDay>31))){toast('请填写有效的名称、时间和整数范围');return false;}return true;}
function updatePlanPreview(){const m=document.getElementById('modal'),s=readPlanDraft(m),box=m.querySelector('#plan-preview');if(!box)return;if(!s.time||!s.anchor||s.every<1||!Number.isInteger(s.every)||!Number.isInteger(s.monthDay)||s.monthDay<1){box.textContent='填写有效的生成时间后，将显示计划摘要。';return;}const preview={...s};refreshPlanSummary(preview);box.textContent=`${preview.cadence}，${preview.focus}。下次计划：${preview.next}（UTC+8，演示时点）。`;}
function reportForPlan(key){if(autoReports[key])return autoReports[key];const s=analysisSchedules[key];return {title:`${esc(s.name)} · 等待首次生成`,range:`${esc(s.focus)} · ${esc(s.cadence)}`,source:'自定义计划预览 · 尚未生成报告',coverage:'暂无报告',description:'计划已保存到当前预览。正式接入后，将按设置读取工单、事件与历史建议，生成独立报告并归档。',metrics:[['生成计划','已配置',''],['已有报告','0','份'],['真实运行','未接入','']],advice:[],emptyTitle:'等待首次计划运行',emptyReason:`下次计划时间：${s.next}（UTC+8）。当前没有这份报告的数据，不会用其他周期的内容替代。`};}
function showAdHocAnalysis(){modal('选择本次分析范围',`<p>可以选择任意日期区间进行一次 AI 分析，不改变自动生成计划。</p><div class="plan-editor"><label>开始日期<input id="adhoc-start" type="date" min="2000-01-01" max="2026-09-06" value="2026-08-31" required></label><label>结束日期<input id="adhoc-end" type="date" min="2000-01-01" max="2026-09-06" value="2026-09-06" required></label></div><div class="adhoc-shortcuts">${[['week','最近 7 天'],['month','本月'],['year','本年']].map(([key,label])=>`<button class="button" data-adhoc-shortcut="${key}">${label}</button>`).join('')}</div><div class="modal-summary">可用演示数据：2026-08-28 — 2026-09-06 10:40<br>分析会标注实际覆盖范围，缺少的数据不会补成 0。</div>`,'分析所选区间（演示）',m=>{const start=m.querySelector('#adhoc-start'),end=m.querySelector('#adhoc-end');if(!start.reportValidity()||!end.reportValidity())return;if(start.value>end.value){toast('开始日期不能晚于结束日期');return;}adHocReport=buildAdHocReport(start.value,end.value);m.close();reportArchive='adhoc';render();toast('已展示所选区间的汇总示例，未调用模型');});}
function buildAdHocReport(start,end){const days=['2026-08-28','2026-08-29','2026-08-30','2026-08-31','2026-09-01','2026-09-02','2026-09-03','2026-09-04','2026-09-05','2026-09-06'],incoming=[12,15,13,16,21,18,15,20,20,24],closed=[5,8,9,14,16,17,15,20,15,18],indices=days.map((d,i)=>d>=start&&d<=end?i:-1).filter(i=>i>=0),total=indices.reduce((n,i)=>n+incoming[i],0),done=indices.reduce((n,i)=>n+closed[i],0),requested=(Date.parse(end)-Date.parse(start))/86400000+1;return {title:'自定义区间 · AI运营分析',range:`请求范围：${start} — ${end}`,source:'手动区间分析示例 · 仅计算已有汇总数据',coverage:indices.length?`有记录 ${indices.length} / ${requested} 天`:'所选区间无数据',description:indices.length?`已有记录覆盖 ${days[indices[0]]} 至 ${days[indices.at(-1)]}${end==='2026-09-06'?' 10:40（当天未结束）':''}。下面仅统计这些记录，不代表缺失日期的运营情况。`:'当前演示数据与所选区间不重叠。缺失数据不记为零，也不生成推测性的运营建议。',metrics:indices.length?[['已有新单',String(total),'单'],['已有闭环',String(done),'单'],['净增积压',(total-done>0?'+':'')+(total-done),'单']]:[['已有新单','—',''],['已有闭环','—',''],['净增积压','—','']],advice:[],emptyTitle:'区间已选定，AI 建议待接入',emptyReason:'设计预览只验证日期选择与已有数据汇总。正式版会进一步关联事件、人员及历史建议，给出有依据的分析。'};}
document.addEventListener('click',e=>{const b=e.target.closest('button');if(!b)return;if(b.dataset.planEdit||b.hasAttribute('data-plan-add')){const m=document.getElementById('modal');capturePlanToggles(m);m.close();editAnalysisPlan(b.dataset.planEdit||null);}if(b.dataset.adhocShortcut){const m=document.getElementById('modal');m.querySelector('#adhoc-start').value={week:'2026-08-31',month:'2026-09-01',year:'2026-01-01'}[b.dataset.adhocShortcut];m.querySelector('#adhoc-end').value='2026-09-06';}if(b.hasAttribute('data-view-adhoc')){reportArchive='adhoc';render();}if(b.dataset.autoAction==='custom-range')showAdHocAnalysis();});
document.addEventListener('change',e=>{if(['plan-frequency','plan-range'].includes(e.target.id)){readPlanDraft(document.getElementById('modal'));document.getElementById('modal').close();renderPlanEditor();}});
document.addEventListener('input',e=>{if(e.target.id.startsWith('plan-'))updatePlanPreview();});

for(const [key,s] of Object.entries(analysisSchedules)){Object.assign(s,{time:'08:30',weekday:1,monthDay:1,yearMonth:1,every:10,unit:'days',anchor:'2026-09-07',rangeDays:30},planDefaults[key]);refreshPlanSummary(s);}
