const paths={expand:'<path d="M8 3H3v5M16 3h5v5M21 16v5h-5M8 21H3v-5"/><path d="M3 3l6 6M21 3l-6 6M21 21l-6-6M3 21l6-6"/>',restore:'<path d="M3 9h6V3M15 3v6h6M21 15h-6v6M9 21v-6H3"/>',chat:'<path d="M21 11a8 8 0 01-8 8H7l-5 3 2-6a9 9 0 1117-5Z"/><path d="M8 10h8M8 14h5"/>',overview:'<rect x="3" y="3" width="7" height="7" rx="1.5"/><rect x="14" y="3" width="7" height="7" rx="1.5"/><rect x="3" y="14" width="7" height="7" rx="1.5"/><rect x="14" y="14" width="7" height="7" rx="1.5"/>',trend:'<path d="M3 3v18h18M6 15l5-5 4 3 6-8"/>',ticket:'<rect x="5" y="3" width="14" height="18" rx="2"/><path d="M9 7h6M9 11h6M9 15h4"/>',staff:'<circle cx="9" cy="7" r="3"/><path d="M3 21v-3a6 6 0 0112 0v3M16 4a3 3 0 010 6M18 13a5 5 0 013 5v3"/>',spark:'<path d="M12 3l2.5 6.5L21 12l-6.5 2.5L12 21l-2.5-6.5L3 12l6.5-2.5ZM20 2v4M18 4h4"/>',settings:'<path d="M4 7h16M4 17h16"/><circle cx="9" cy="7" r="3" fill="currentColor"/><circle cx="16" cy="17" r="3" fill="currentColor"/>',arrow:'<path d="M4 12h16M15 7l5 5-5 5"/>',calendar:'<rect x="3" y="5" width="18" height="16" rx="2"/><path d="M7 3v4M17 3v4M3 11h18M8 15h1M15 15h1"/>',download:'<path d="M12 3v12M7 10l5 5 5-5M4 16v5h16v-5"/>',clock:'<circle cx="12" cy="12" r="9"/><path d="M12 7v5l3 2"/>',check:'<circle cx="12" cy="12" r="9"/><path d="M8 12l3 3 5-6"/>',alert:'<path d="M10 4L2 18a2 2 0 002 3h16a2 2 0 002-3L14 4a2 2 0 00-4 0Z"/><path d="M12 9v5M12 17v.2"/>',pause:'<circle cx="12" cy="12" r="9"/><path d="M9 8v8M15 8v8"/>',search:'<circle cx="10" cy="10" r="6"/><path d="M15 15l6 6"/>',help:'<circle cx="12" cy="12" r="9"/><path d="M9 8a3 3 0 016 0c0 2-3 2-3 5M12 17v.2"/>',close:'<path d="M6 6l12 12M6 18L18 6"/>',refresh:'<path d="M20 10a8 8 0 00-14-5L3 8m0-5v5h5M4 14a8 8 0 0014 5l3-3m0 5v-5h-5"/>',plus:'<path d="M12 4v16M4 12h16"/>'};
const icon=n=>`<svg class="icon" viewBox="0 0 24 24" aria-hidden="true">${paths[n]||paths.ticket}</svg>`;
const esc=s=>String(s).replace(/[&<>"']/g,c=>({'&':'&amp;','<':'&lt;','>':'&gt;','"':'&quot;',"'":'&#39;'}[c]));
const navs=[['insights','spark','AI智能分析'],['overview','overview','运营总览'],['trends','trend','工单趋势'],['tickets','ticket','工单明细'],['staff','staff','人员与负载'],['accounts','staff','企微账号'],['messages','chat','消息日志'],['settings','settings','配置管理']];
let page='overview',period='week',configTab='routing',staffGroup='全部小组',ticketQuery='',ticketStatus='全部状态',ticketGroup='全部小组',lastFocus=null;
const tickets=[
{id:'E174',room:'A-1208',title:'空调不制冷，需要上门检修',type:'报修',group:'房修组',owner:'待接单',status:'无人接单',created:'10:08',elapsed:'32 分钟',priority:'优先',events:[['10:08','工单创建','住户反馈空调不制冷，房号 A-1208。'],['10:08','自动识别 · 报修','根据空调关键词，路由至房修组。'],['10:09','派单至房修组','通知一档在岗人员。'],['10:24','发送接单提醒','超过 15 分钟仍未接单。'],['10:38','标记无人接单','等待运营介入，建议确认当班人员。']]},
{id:'E169',room:'B-0603',title:'浴室水龙头持续漏水',type:'报修',group:'房修组',owner:'王师傅',status:'已升级 L2',created:'09:48',elapsed:'52 分钟',priority:'优先'},
{id:'E163',room:'A-0916',title:'网络频繁掉线，无法正常办公',type:'IT网络',group:'客服组',owner:'李敏',status:'挂起中',created:'09:20',elapsed:'10:30 提醒',priority:'普通'},
{id:'E173',room:'B-1105',title:'补充两套浴巾与洗漱用品',type:'清洁',group:'客房组',owner:'陈阿姨',status:'处理中',created:'10:05',elapsed:'35 分钟',priority:'普通'},
{id:'E172',room:'A-0802',title:'咨询月底续租办理流程',type:'续退租',group:'客服组',owner:'李敏',status:'已闭环',created:'09:58',elapsed:'18 分钟',priority:'普通'},
{id:'E171',room:'C-0302',title:'门锁电量低，申请更换电池',type:'报修',group:'房修组',owner:'张师傅',status:'处理中',created:'09:55',elapsed:'45 分钟',priority:'普通'},
{id:'E170',room:'B-0716',title:'预约下午房间清洁',type:'清洁',group:'客房组',owner:'刘阿姨',status:'已接单',created:'09:50',elapsed:'50 分钟',priority:'普通'},
{id:'E168',room:'C-0608',title:'请配送一桶饮用水',type:'送水',group:'客房组',owner:'陈阿姨',status:'已闭环',created:'09:42',elapsed:'21 分钟',priority:'普通'},
{id:'E167',room:'A-0511',title:'走廊照明灯闪烁',type:'报修',group:'房修组',owner:'待接单',status:'待接单',created:'09:40',elapsed:'1 小时',priority:'普通'},
{id:'E166',room:'B-0218',title:'退租押金到账进度咨询',type:'咨询',group:'客服组',owner:'赵悦',status:'已闭环',created:'09:35',elapsed:'12 分钟',priority:'普通'},
{id:'E165',room:'C-1006',title:'需要更换床单',type:'清洁',group:'客房组',owner:'刘阿姨',status:'处理中',created:'09:29',elapsed:'1 小时 11 分',priority:'普通'},
{id:'E164',room:'A-1103',title:'淋浴花洒支架松动',type:'报修',group:'房修组',owner:'张师傅',status:'已闭环',created:'09:25',elapsed:'38 分钟',priority:'普通'}];
const staff=[['王师傅','房修组',8,5,'8.2','47'],['陈阿姨','客房组',6,2,'3.5','26'],['李敏','客服组',5,2,'2.8','18'],['张师傅','房修组',3,1,'4.1','36'],['刘阿姨','客房组',1,1,'4.6','29'],['赵悦','客服组',1,0,'2.1','15']];
const routes=[['报修','空调、漏水、门锁、灯具','房修组','默认规则'],['清洁','清洁、布草、浴巾、洗漱用品','客房组','默认规则'],['IT网络','网络、Wi-Fi、宽带、掉线','客服组','学习规则'],['送水 / 送餐','饮用水、配送、餐食','客房组','默认规则'],['续退租 / 咨询','续租、退租、押金、账单','客服组','默认规则']];
const status=s=>`<span class="status ${/无人|升级/.test(s)?'attention':/处理|接单/.test(s)?'blue':'muted'}">${/无人|升级/.test(s)?'! ':s==='已闭环'?'✓ ':s==='挂起中'?'Ⅱ ':''}${s}</span>`;
function renderIcons(){document.querySelectorAll('[data-icon]').forEach(e=>e.outerHTML=icon(e.dataset.icon));}
function heading(title,subtitle,actions=''){return `<div class="page-heading"><div><div class="eyebrow">OPERATIONS / ${page==='overview'?'OVERVIEW':page.toUpperCase()}</div><h1>${title}</h1><p>${subtitle}</p></div><svg class="watermark" viewBox="0 0 200 110"><path d="M50 10l22 13v26L50 62 28 49V23ZM96 35l22 13v26L96 87 74 74V48ZM142 10l22 13v26l-22 13-22-13V23ZM142 62l22 13v26l-22 13-22-13V75Z"/></svg><div class="heading-actions">${actions}</div></div>`;}
const dateButton=()=>`<button class="button" data-action="date">${icon('calendar')}2026年9月6日<span>⌄</span></button>`;
function kpis(){return `<div class="kpis">${[['ticket','今日新单','24','单','较昨日 <b>↑ 4 单</b>'],['clock','待闭环','37','单','当前全部未闭环工单'],['check','今日闭环','18','单','较昨日 <b>↑ 3 单</b>'],['alert','待接单','4','单','含 <b>2 单无人接单</b>'],['pause','挂起中','6','单','今日待跟进 <b>2 单</b>']].map(([i,l,v,u,n])=>`<div class="kpi"><div class="kpi-top"><span class="medallion">${icon(i)}</span>${l}</div><div class="kpi-value">${v}<small>${u}</small></div><div class="kpi-note">${n}</div></div>`).join('')}</div>`;}
const datasets={week:{labels:['8/31','9/01','9/02','9/03','9/04','9/05','9/06'],incoming:[16,21,18,15,20,20,24],closed:[14,16,17,15,20,15,18],max:30,caption:'近 7 天 · 按自然日统计',total:134,done:115},day:{labels:['00:00','02:00','04:00','06:00','08:00','10:00'],incoming:[1,0,1,2,8,12],closed:[0,0,1,1,7,9],max:15,caption:'今日 · 每 2 小时汇总',total:24,done:18},month:{labels:['8/28','8/29','8/30','8/31','9/01','9/02','9/03','9/04','9/05','9/06'],incoming:[12,15,13,16,21,18,15,20,20,24],closed:[5,8,9,14,16,17,15,20,15,18],max:30,caption:'近 30 天 · 仅展示已有的 10 天演示记录',total:174,done:137}};
function chart(){const d=datasets[period],w=window.innerWidth<720?360:720,h=184,l=29,r=21,top=14,bottom=30,x=i=>l+i*(w-l-r)/(d.labels.length-1),y=v=>top+(d.max-v)/d.max*(h-top-bottom),p=a=>a.map((v,i)=>`${i?'L':'M'}${x(i)},${y(v)}`).join(' ');return `<div class="chart-meta"><span class="legend"><i></i>新建工单</span><span class="legend closed"><i></i>闭环工单</span><span style="margin-left:auto">单位：单</span></div><svg class="chart" viewBox="0 0 ${w} ${h}" role="img" aria-label="${d.caption}，新建 ${d.total} 单，闭环 ${d.done} 单"><defs><linearGradient id="area" x1="0" y1="0" x2="0" y2="1"><stop offset="0%" stop-color="var(--beemax-blue-600)" stop-opacity=".13"/><stop offset="100%" stop-color="var(--beemax-blue-600)" stop-opacity=".015"/></linearGradient></defs>${[0,1,2,3].map(v=>{let n=v*d.max/3;return `<line class="grid" x1="${l}" y1="${y(n)}" x2="${w-r}" y2="${y(n)}"/><text x="0" y="${y(n)+4}">${n}</text>`}).join('')}<path d="${p(d.incoming)} L${x(d.labels.length-1)},${y(0)} L${l},${y(0)} Z" fill="url(#area)"/><path class="line-closed" d="${p(d.closed)}"/><path class="line-main" d="${p(d.incoming)}"/>${d.labels.map((v,i)=>`<circle class="point" cx="${x(i)}" cy="${y(d.incoming[i])}" r="3"><title>${v}：新建 ${d.incoming[i]} 单，闭环 ${d.closed[i]} 单</title></circle><text x="${x(i)}" y="${h-6}" text-anchor="middle">${v}</text>`).join('')}</svg>${page==='overview'?'<div class="chart-stats"><span>今日平均响应<strong>5.4<small> 分钟</small></strong></span><span>今日平均闭环<strong>42<small> 分钟</small></strong></span><span>累计完成率<strong>78.7<small>%</small></strong></span></div>':`<div class="chart-stats"><span>期间新建<strong>${d.total}<small> 单</small></strong></span><span>期间闭环<strong>${d.done}<small> 单</small></strong></span><span>净增积压<strong>+${d.total-d.done}<small> 单</small></strong></span></div>`}`;}
function trendPanel(big=false){return `<section class="panel ${big?'large-chart':''}"><div class="panel-heading"><div><h2>工单流转趋势</h2><div class="subtext">${datasets[period].caption}</div></div><div class="segmented" aria-label="趋势时间范围">${[['day','日'],['week','周'],['month','月']].map(([k,t])=>`<button data-period="${k}" class="${period===k?'active':''}" aria-pressed="${period===k}">${t}</button>`).join('')}</div></div><div class="primary-grid"><div class="chart-wrap">${chart()}</div><aside class="insight-side"><div class="insight-title">${icon('spark')}运营洞察<span class="mini-tag">示例</span></div><h3>房修组的接单负载<br>值得关注</h3><p>今日房修单占新单的 46%。王师傅承担该组 73% 的接单，可考虑调整二档支援。</p><div class="distribution"><span style="width:46%"></span><span style="width:29%"></span><span style="width:25%"></span></div><div class="distribution-label"><span>房修 46%</span><span>客房 29%</span><span>客服 25%</span></div><a class="text-link" href="#insights">查看分析与建议 ${icon('arrow')}</a></aside></div></section>`;}
function attention(){return `<section class="panel"><div class="panel-heading"><h2>优先关注<span class="count-chip">3</span></h2><a href="#tickets" class="text-link">全部工单 ${icon('arrow')}</a></div><div class="table-box"><table><thead><tr><th>工单 / 房号</th><th>当前状态</th><th>负责人</th><th>操作</th></tr></thead><tbody>${tickets.slice(0,3).map(t=>`<tr><td><strong>${t.room}</strong><span class="ticket-id">${t.id}</span><small>${t.title.length>16?t.title.slice(0,16)+'…':t.title}</small></td><td>${status(t.status)}<small>${t.elapsed}</small></td><td>${t.owner}</td><td><button class="text-link" data-ticket="${t.id}">查看 ${icon('arrow')}</button></td></tr>`).join('')}</tbody></table></div><div class="panel-footer"><span class="mini-info">${icon('clock')}先关注无人接单、升级与到期挂起</span><span>截至 10:40</span></div></section>`;}
function staffMini(){return `<section class="panel"><div class="panel-heading"><h2>当班人员负载</h2><a class="text-link" href="#staff">人员明细 ${icon('arrow')}</a></div><div class="table-box"><table><thead><tr><th>接单人</th><th>今日接单</th><th>待办</th><th>平均响应</th></tr></thead><tbody>${staff.slice(0,3).map(s=>`<tr><td><div class="person"><span class="avatar">${s[0][0]}</span><div>${s[0]}<small>${s[1]} · 一档</small></div></div></td><td>${s[2]} 单<div class="load"><i style="width:${s[2]/8*100}%"></i></div></td><td>${s[3]} 单</td><td>${s[4]} <small style="display:inline">分钟</small></td></tr>`).join('')}</tbody></table></div><div class="panel-footer"><span>今日当班 6 人 · 已接单 24 单</span><span>按接单量排序</span></div></section>`;}
function overview(){return heading('每一单，都有着落。','丁总，上午好。今天是 2026年9月6日，星期日。',dateButton()+`<button class="button" data-action="export">${icon('download')}导出简报</button>`)+kpis()+trendPanel()+`<div class="lower-grid">${attention()}${staffMini()}</div>`;}
const bars=(rows)=>`<div class="horizontal-bars">${rows.map(([n,v,max,unit])=>`<div class="bar-line"><span>${n}</span><div class="bar-track"><i style="width:${v/max*100}%"></i></div><span>${v}${unit||' 单'}</span></div>`).join('')}</div>`;
function trends(){return heading('看见趋势，提前行动。','从新单、闭环与积压，了解运营节奏的变化。',`<button class="button" data-action="export">${icon('download')}导出简报</button>`)+trendPanel(true)+`<div class="section-grid"><section class="panel"><div class="panel-heading"><h2>工单类型分布</h2><span class="subtext">今日新建 · 24 单</span></div>${bars([['报修',11,11],['清洁',5,11],['IT网络',1,11],['送水',2,11],['续退租',3,11],['咨询',2,11]])}</section><section class="panel"><div class="panel-heading"><h2>待闭环状态分布</h2><span class="subtext">当前存量 · 37 单</span></div>${bars([['处理中',24,24],['待接单',4,24],['已升级',3,24],['挂起中',6,24]])}<div class="panel-footer">待接单含 2 单无人接单；闭环状态统一合并统计。</div></section></div>`;}
function ticketRows(){let a=tickets.filter(t=>(ticketStatus==='全部状态'||t.status===ticketStatus)&&(ticketGroup==='全部小组'||t.group===ticketGroup)&&`${t.id} ${t.room} ${t.title} ${t.owner} ${t.type}`.toLowerCase().includes(ticketQuery.toLowerCase()));return a.length?a.map(t=>`<tr><td><span class="subject">${t.title}</span><small>${t.id} · ${t.room} · ${t.type}</small></td><td>${status(t.status)}</td><td>${t.group}</td><td>${t.owner}</td><td>09-06 ${t.created}</td><td><button class="text-link" data-ticket="${t.id}">详情 ${icon('arrow')}</button></td></tr>`).join(''):`<tr><td colspan="6"><div class="empty">没有匹配的工单<br><small>试试其他房号、负责人或状态</small></div></td></tr>`;}
function ticketPage(){return heading('工单明细','从一条问题，到一次完整闭环。追踪每个处理节点。',dateButton())+`<div class="panel"><div class="filters"><label class="search">${icon('search')}<input id="ticket-search" aria-label="搜索工单" placeholder="搜索工单、房号、问题或负责人" value="${esc(ticketQuery)}"></label><select id="ticket-status" aria-label="筛选状态">${['全部状态','无人接单','待接单','处理中','已接单','已升级 L2','挂起中','已闭环'].map(s=>`<option ${ticketStatus===s?'selected':''}>${s}</option>`).join('')}</select><select id="ticket-group" aria-label="筛选小组">${['全部小组','房修组','客房组','客服组'].map(s=>`<option ${ticketGroup===s?'selected':''}>${s}</option>`).join('')}</select><button class="text-link" data-action="reset-filters">重置</button></div><div class="table-box" style="margin-top:0"><table class="all-tickets"><thead><tr><th>问题 / 工单</th><th>状态</th><th>负责小组</th><th>负责人</th><th>创建时间</th><th>操作</th></tr></thead><tbody id="ticket-body">${ticketRows()}</tbody></table></div><div class="panel-footer"><span>12 条演示记录 · 用于预览筛选与时间线</span><span>第 1 页 / 共 1 页</span></div></div>`;}
function staffPage(){const rows=staff.filter(s=>staffGroup==='全部小组'||s[1]===staffGroup);return heading('合理分工，从看见负载开始。','今日在岗与接单表现 · 2026年9月6日',`<a class="button" href="#settings">${icon('calendar')}查看排班</a>`)+`<div class="pill-tabs">${['全部小组','房修组','客房组','客服组'].map(g=>`<button class="${staffGroup===g?'active':''}" data-staff-group="${g}">${g}</button>`).join('')}</div><section class="panel"><div class="summary-rail"><span>当班人数<strong>${rows.length}<small> 人</small></strong></span><span>今日接单<strong>${rows.reduce((n,s)=>n+s[2],0)}<small> 单</small></strong></span><span>个人最多待办<strong>${Math.max(...rows.map(s=>s[3]))}<small> 单</small></strong></span></div><div class="table-box" style="margin-top:0"><table><thead><tr><th>人员 / 小组</th><th>今日接单 / 占比</th><th>当前待办</th><th>平均响应</th><th>平均处理</th></tr></thead><tbody>${rows.map(s=>`<tr><td><div class="person"><span class="avatar">${s[0][0]}</span><div>${s[0]}<small>${s[1]} · 当班</small></div></div></td><td>${s[2]} 单 <small style="display:inline">/ ${Math.round(s[2]/24*100)}%</small><div class="load"><i style="width:${s[2]/8*100}%"></i></div></td><td>${s[3]} 单</td><td>${s[4]} 分钟</td><td>${s[5]} 分钟</td></tr>`).join('')}</tbody></table></div><div class="panel-footer">平均响应：接单 − 创建；平均处理：闭环 − 接单。仅纳入时间戳完整的样本。</div></section><div class="note-band">${icon('spark')}　今日房修组共接单 11 单，其中王师傅 8 单、张师傅 3 单。建议结合工单难度和在岗时长评估分配，避免仅按单量判断绩效。</div>`;}
function configContent(){if(configTab==='connection')return connectionSettings();if(configTab==='access')return connectionPermissions();if(configTab==='routing')return `<div class="config-title"><div><h2>路由规则</h2><p>按工单类型与关键词，找到合适的处理小组。</p></div><button class="button primary" data-action="add-rule">${icon('plus')}新增规则</button></div><div class="table-box" style="margin-top:0"><table><thead><tr><th>问题类型</th><th>匹配关键词</th><th>处理小组</th><th>来源</th><th>操作</th></tr></thead><tbody>${routes.map((r,i)=>`<tr><td>${esc(r[0])}</td><td>${esc(r[1])}</td><td>${esc(r[2])}</td><td><span class="status ${r[3]==='学习规则'?'blue':'muted'}">${r[3]}</span></td><td><button class="text-link" data-rule="${i}">编辑</button></td></tr>`).join('')}</tbody></table></div><div class="panel-footer">规则修改先展示变更确认，确认后仅在当前设计预览中生效。</div>`;
if(configTab==='roster')return `<div class="config-title"><div><h2>当班排班</h2><p>2026年9月6日 · 默认排班与按日覆盖。</p></div><button class="button" data-action="roster">${icon('calendar')}调整排班</button></div><div class="table-box" style="margin-top:0"><table><thead><tr><th>小组</th><th>一档人员</th><th>二档支援</th><th>来源</th></tr></thead><tbody>${[['房修组','王师傅','张师傅'],['客房组','陈阿姨','刘阿姨'],['客服组','李敏','赵悦']].map(r=>`<tr><td>${r[0]}</td><td>${r[1]}</td><td>${r[2]}</td><td><span class="status muted">默认排班</span></td></tr>`).join('')}</tbody></table></div>`;
if(configTab==='parameters')return `<div class="config-title"><div><h2>派单与提醒</h2><p>让响应有时限，让跟进有节奏。</p></div></div>${[['升级间隔','未接单时，进入下一档通知的等待时长','15 分钟'],['接单提醒','首次提醒在岗人员接单的时间','5 分钟'],['挂起提前提醒','在约定跟进时间之前提醒负责人','10 分钟']].map((r,i)=>`<div class="config-row"><div><h3>${r[0]}</h3><p>${r[1]}</p></div><button class="button" data-param="${i}">${r[2]}　编辑</button></div>`).join('')}`;
if(configTab==='learning')return `<div class="config-title"><div><h2>学习与灰度</h2><p>在人工可控的范围内，持续积累处理经验。</p></div></div>${[['转单学习自动应用','将人工转派中学到的规则用于后续派单',false],['路由灰度观察','记录新路由的判断结果，供人工评估',true]].map(([t,p,on],i)=>`<div class="config-row"><div><h3>${t} <span class="status muted">${on?'已开启':'已关闭'}</span></h3><p>${p}</p></div><button class="switch ${on?'':'off'}" role="switch" aria-checked="${on}" aria-label="${t}" data-toggle="${i}"></button></div>`).join('')}`;

return `<div class="config-title"><div><h2>配置变更记录</h2><p>谁在何时改了什么，每一步均可回看。</p></div></div><div class="table-box" style="margin-top:0"><table><thead><tr><th>时间</th><th>操作人</th><th>变更内容</th><th>结果</th></tr></thead><tbody>${audit.map(r=>`<tr><td>${esc(r[0])}</td><td>${esc(r[1])}</td><td>${esc(r[2])}</td><td><span class="status muted">${esc(r[3])}</span></td></tr>`).join('')}</tbody></table></div>`;}
let audit=[['09-06 09:10','丁总','房修组二档人员调整为张师傅','示例记录'],['09-05 16:32','丁总','升级间隔：20 分钟 → 15 分钟','示例记录'],['09-05 11:08','owner','开启路由灰度观察','示例记录']];
function settings(){return heading('规则清楚，协作有序。','管理派单规则与在岗安排，每次变更都有记录。',`<span class="status muted">${configTab==='connection'&&ownerPreview?'owner 表单预览':'运营管理员视图'}</span>`)+`<div class="tabbar" role="tablist">${[['connection','连接设置'],['routing','路由规则'],['roster','排班人员'],['parameters','派单参数'],['access','群与权限'],['learning','学习与灰度'],['audit','变更记录']].map(([k,t])=>`<button role="tab" aria-selected="${configTab===k}" data-config="${k}" class="${configTab===k?'active':''}">${t}</button>`).join('')}</div><section class="panel">${configContent()}</section>`;}
function render(){if(location.hash==='#assistant'){history.replaceState(null,'','#overview');assistantWidgetOpen=true;}page=location.hash.slice(1)||'overview';if(page!=='agent'&&!navs.some(n=>n[0]===page))page='overview';document.getElementById('navigation').innerHTML=navs.map(([p,i,n],idx)=>`${p==='overview'?'<div class="nav-separator"></div><div class="nav-label nav-group-label">工作空间</div>':p==='accounts'?'<div class="nav-separator"></div><div class="nav-label nav-group-label">连接管理</div>':p==='settings'?'<div class="nav-separator"></div>':''}<a href="#${p}" class="nav-item ${['insights','assistant'].includes(p)?'ai-nav-item':''} ${(p===page||p==='accounts'&&page==='agent')?'active':''}" ${(p===page||p==='accounts'&&page==='agent')?'aria-current="page"':''}>${icon(i)}<span>${n}</span>${p==='tickets'?'<span class="nav-count">37</span>':''}</a>`).join('');document.getElementById('crumb').textContent=page==='agent'?'企微账号 / Agent 详情':navs.find(n=>n[0]===page)[2];document.getElementById('content').innerHTML=({overview,trends,tickets:ticketPage,staff:staffPage,insights,settings,accounts:accountsPage,messages:messagesPage,agent:agentPage})[page]();renderIcons();document.body.classList.remove('nav-open');renderAssistantWidget();connectionTimerSync();}
function toast(s){let el=document.getElementById('toast');el.textContent=s;el.classList.add('show');clearTimeout(window.toastTimer);window.toastTimer=setTimeout(()=>el.classList.remove('show'),3500);}
function closeDrawer(){window.activeTicketId=null;document.getElementById('drawer').hidden=true;document.getElementById('overlay').hidden=true;document.body.style.overflow='';lastFocus?.focus();}
function openTicket(id){if(assistantWidgetOpen)closeAssistantWidget();window.activeTicketId=id;const t=tickets.find(t=>t.id===id);lastFocus=document.activeElement;const events=t.events||[[t.created,'工单创建',`住户提交${t.type}问题，房号 ${t.room}。`],[t.created,'完成分类与派单',`识别为${t.type}，派单至${t.group}。`],['—','当前状态',`${t.status} · ${t.owner}。演示记录暂未补充其余事件时间戳。`]];document.getElementById('drawer').innerHTML=`<div class="drawer-top"><span>工单详情 / ${t.id}</span><button class="icon-button" data-action="close-drawer" aria-label="关闭工单详情">${icon('close')}</button></div><h2>${t.title}</h2>${status(t.status)} <span class="status muted">${t.priority}处理</span><div class="detail-meta"><div><span>房号</span>${t.room}</div><div><span>工单类型</span>${t.type}</div><div><span>负责小组</span>${t.group}</div><div><span>当前负责人</span>${t.owner}</div></div><div class="subtext" style="margin-bottom:9px">住户原文 · 演示</div><div class="quote">“${t.title}，麻烦安排处理一下，谢谢。”</div><h3 style="font-size:15px;margin-top:26px">完整流转时间线 <span class="count-chip">${events.length}</span></h3><div class="timeline">${events.map(([time,n,d])=>`<div class="event"><div><strong>${n}</strong><time>${time}</time></div><p>${d}</p></div>`).join('')}</div><div class="note-band">${t.status==='无人接单'?'建议先确认在岗人员。催办将提醒负责小组接单。':'结合处理进度，确认下一步动作。'}<br>设计预览中的操作不会发送通知。</div><div class="drawer-actions"><button class="button primary" data-command="催办" data-id="${id}" ${t.status==='已闭环'?'disabled':''}>${icon('alert')}催办</button><button class="button" data-command="转派" data-id="${id}" ${t.status==='已闭环'?'disabled':''}>转派</button><button class="button" data-command="${t.status==='挂起中'?'恢复':'挂起'}" data-id="${id}" ${t.status==='已闭环'?'disabled':''}>${t.status==='挂起中'?'恢复':'挂起'}</button><button class="button" data-command="完成" data-id="${id}" ${t.status==='已闭环'?'disabled':''}>完成工单</button></div>`;document.getElementById('overlay').hidden=false;document.getElementById('drawer').hidden=false;document.body.style.overflow='hidden';document.querySelector('[data-action="close-drawer"]').focus();}
function modal(title,body,confirm='知道了',callback=null){const m=document.getElementById('modal');m.classList.remove('plan-dialog');m.innerHTML=`<h2>${title}</h2>${body}<div class="modal-actions">${callback?'<button class="button" id="modal-cancel">取消</button>':''}<button class="button primary" id="modal-confirm">${confirm}</button></div>`;m.showModal();document.getElementById('modal-cancel')?.addEventListener('click',()=>m.close());document.getElementById('modal-confirm').onclick=()=>{if(callback){callback(m);}else m.close();};}
function editRule(idx){const r=idx===undefined?['','','房修组','人工规则']:routes[idx];modal(idx===undefined?'新增路由规则':'编辑路由规则',`<p>设置匹配条件与处理小组，下一步将核对变更。</p><label>问题类型<input id="rule-type" value="${esc(r[0])}" placeholder="例如：报修"></label><label>匹配关键词<input id="rule-keywords" value="${esc(r[1])}" placeholder="多个关键词以顿号分隔"></label><label>处理小组<select id="rule-group">${['房修组','客房组','客服组'].map(s=>`<option ${s===r[2]?'selected':''}>${s}</option>`).join('')}</select></label>`,'预览变更',m=>{const name=m.querySelector('#rule-type').value.trim(),keywords=m.querySelector('#rule-keywords').value.trim(),group=m.querySelector('#rule-group').value;if(!name||!keywords){toast('请填写问题类型与关键词');return;}m.close();modal('确认路由变更',`<p>请确认以下规则。此操作仅修改当前预览，并添加演示审计记录。</p><div class="modal-summary">类型：${esc(name)}<br>关键词：${esc(keywords)}<br>处理小组：${esc(r[2])} → <strong>${esc(group)}</strong><br>操作人：丁总</div>`,'确认修改（演示）',m2=>{const row=[name,keywords,group,'人工规则'];idx===undefined?routes.push(row):routes[idx]=row;audit.unshift(['本次预览','丁总',`${name}规则 → ${group}`,'预览变更']);m2.close();render();toast('预览规则已更新，已记录到变更记录');});});}
function exportReport(){const text=`工单运营简报（设计稿演示数据）\n日期：2026-09-06 10:40 UTC+8\n今日新建：24 单\n当前待闭环：37 单\n今日闭环：18 单\n待接单：4 单（含无人接单 2 单）\n挂起：6 单\n近7天新建：134 单；闭环：115 单；积压净增：19 单\n\n本文件仅用于 UI 设计预览，不代表真实运营情况。\n`;const url=URL.createObjectURL(new Blob([text],{type:'text/plain;charset=utf-8'})),a=document.createElement('a');a.href=url;a.download='工单运营简报-演示数据.txt';a.click();setTimeout(()=>URL.revokeObjectURL(url),1000);toast('演示简报已导出');}
document.addEventListener('click',e=>{const el=e.target.closest('button,a');if(!el)return;if(el.dataset.period){period=el.dataset.period;render();}if(el.dataset.ticket)openTicket(el.dataset.ticket);if(el.dataset.config){configTab=el.dataset.config;render();}if(el.dataset.staffGroup){staffGroup=el.dataset.staffGroup;render();}if(el.dataset.rule!==undefined)editRule(Number(el.dataset.rule));if(el.dataset.command){const cmd=el.dataset.command;modal(`确认${cmd}工单 ${el.dataset.id}`,`<p>${cmd==='催办'?'正式系统将向负责小组发送催办通知。':`正式系统将执行${cmd}并记录操作人。`}当前设计稿仅展示操作确认。</p>${cmd==='转派'?'<label>转派至<select><option>房修组 · 张师傅</option><option>客房组 · 陈阿姨</option><option>客服组 · 李敏</option></select></label>':cmd==='挂起'?'<label>挂起原因<input placeholder="例如：等待配件到货"></label><label>跟进时间<input type="datetime-local" value="2026-09-06T15:00"></label>':''}<div class="modal-summary">工单：${el.dataset.id}<br>操作人：丁总<br>操作结果：预览，不会改变真实工单</div>`,'确认（演示）',m=>{m.close();toast(`已预览${cmd}操作，未发送真实通知`);});}
if(el.dataset.param!==undefined){const names=['升级间隔','接单提醒','挂起提前提醒'];modal(`调整${names[el.dataset.param]}`,`<label>时长（分钟）<input type="number" min="1" max="120" value="15"></label><p>当前仅预览参数编辑及确认流程。</p>`,'确认（演示）',m=>{m.close();toast('已预览参数变更，未修改实际配置');});}
if(el.dataset.toggle!==undefined){modal('确认学习配置变更',`<p>${el.getAttribute('aria-label')}：${el.getAttribute('aria-checked')==='true'?'开启 → 关闭':'关闭 → 开启'}。</p><p>当前仅预览确认流程，不改变真实配置。</p>`,'确认（演示）',m=>{m.close();toast('已预览开关变更，未修改实际配置');});}
switch(el.dataset.action){case'close-drawer':closeDrawer();break;case'export':exportReport();break;case'help':modal('工单运营中心 · 设计预览','<p>基于 BeeMax 官方品牌系统制作的交互设计稿。包含运营总览、工单趋势、工单明细、人员负载、AI智能分析、AI助手与配置管理。</p><p>所有数据均为演示。可体验趋势切换、工单筛选、时间线和路由编辑确认。预览不连接业务服务。</p>');break;case'date':modal('查看日期','<label>运营日期<input type="date" value="2026-09-06" min="2026-09-06" max="2026-09-06"></label><p>本版设计稿提供 9月6日 演示快照。趋势页可切换日、周、月。</p>');break;case'analysis':toast('当前展示固定分析示例；正式版将基于实时数据生成');break;case'add-rule':editRule();break;case'reset-filters':ticketQuery='';ticketStatus='全部状态';ticketGroup='全部小组';render();break;case'roster':modal('调整当班排班','<label>日期<input type="date" value="2026-09-06"></label><label>小组<select><option>房修组</option><option>客房组</option><option>客服组</option></select></label><label>一档人员<input value="王师傅"></label><label>二档支援<input value="张师傅"></label><p>设计预览 · 正式版修改将覆盖所选日期排班并留痕。</p>','确认（演示）',m=>{m.close();toast('已预览排班调整，未修改实际人员安排');});break;case'access':modal('新增一线人员','<label>人员名称<input placeholder="填写姓名"></label><label>所属小组<select><option>房修组</option><option>客房组</option><option>客服组</option></select></label><p>权限：本组接单与完成。正式开通后，将向 owner 同步留痕。</p>','确认（演示）',m=>{m.close();toast('已预览人员授权，未开通真实权限');});break;}});
document.addEventListener('input',e=>{if(e.target.id==='ticket-search'){ticketQuery=e.target.value;document.getElementById('ticket-body').innerHTML=ticketRows();}});document.addEventListener('change',e=>{if(e.target.id==='ticket-status'){ticketStatus=e.target.value;document.getElementById('ticket-body').innerHTML=ticketRows();}if(e.target.id==='ticket-group'){ticketGroup=e.target.value;document.getElementById('ticket-body').innerHTML=ticketRows();}});
document.getElementById('overlay').onclick=closeDrawer;
document.addEventListener('keydown',e=>{const drawer=document.getElementById('drawer');if(e.key==='Escape'&&!drawer.hidden&&!document.getElementById('modal').open)closeDrawer();if(e.key==='Tab'&&!drawer.hidden&&!document.getElementById('modal').open){const items=[...drawer.querySelectorAll('button:not(:disabled),a,input,select')];if(e.shiftKey&&document.activeElement===items[0]){e.preventDefault();items.at(-1).focus();}else if(!e.shiftKey&&document.activeElement===items.at(-1)){e.preventDefault();items[0].focus();}}});
window.addEventListener('hashchange',()=>{closeDrawer();assistantPageChanged();render();window.scrollTo(0,0);});render();

let narrow=window.innerWidth<720;window.addEventListener("resize",()=>{const next=window.innerWidth<720;if(next!==narrow){narrow=next;render();}});
