// Resizable floating assistant; sizes live only in the current design preview.
const assistantManualFrames={compact:null,expanded:null};
let assistantResizeSession=null,assistantResizeRenderPending=false;
const assistantClamp=(value,min,max)=>Math.min(Math.max(value,min),max);
function assistantResizeHandles(){return ['n','e','s','w','ne','se','sw','nw'].map(edge=>`<button type="button" class="assistant-resize-handle resize-${edge}" data-assistant-edge="${edge}" tabindex="${edge==='se'?'0':'-1'}" aria-label="${edge==='se'?'调整助手窗口大小':'拖动调整窗口'+({n:'上边',e:'右边',s:'下边',w:'左边',ne:'右上角',sw:'左下角',nw:'左上角'}[edge]||'右下角')}" title="拖动调整大小${edge==='se'?'；也可用方向键调整':''}"></button>`).join('');}
function assistantFrameBounds(){return {padding:8,width:window.innerWidth,height:window.innerHeight,minWidth:Math.min(340,window.innerWidth-16),minHeight:Math.min(440,window.innerHeight-16)};}
function assistantBoundFrame(frame,b=assistantFrameBounds()){const width=assistantClamp(frame.width,b.minWidth,b.width-2*b.padding),height=assistantClamp(frame.height,b.minHeight,b.height-2*b.padding);return {left:assistantClamp(frame.left,b.padding,b.width-b.padding-width),top:assistantClamp(frame.top,b.padding,b.height-b.padding-height),width,height};}
function assistantResizeFrame(start,edge,dx,dy,b=assistantFrameBounds()){let left=start.left,right=start.left+start.width,top=start.top,bottom=start.top+start.height;if(edge.includes('w'))left=assistantClamp(start.left+dx,b.padding,right-b.minWidth);if(edge.includes('e'))right=assistantClamp(right+dx,left+b.minWidth,b.width-b.padding);if(edge.includes('n'))top=assistantClamp(start.top+dy,b.padding,bottom-b.minHeight);if(edge.includes('s'))bottom=assistantClamp(bottom+dy,top+b.minHeight,b.height-b.padding);return assistantBoundFrame({left,top,width:right-left,height:bottom-top},b);}
function assistantWindowFrame(){const r=document.getElementById('assistant-widget').getBoundingClientRect();return {left:r.left,top:r.top,width:r.width,height:r.height};}
function applyAssistantManualFrame(){const host=document.getElementById('assistant-widget');if(!host)return;const mode=assistantWidgetExpanded?'expanded':'compact',stored=assistantManualFrames[mode];host.classList.toggle('assistant-user-sized',!!stored);if(stored){const f=assistantBoundFrame(stored);for(const name of ['left','top','width','height'])host.style[name]=`${f[name]}px`;}else for(const name of ['left','top','width','height'])host.style.removeProperty(name);}
function finishAssistantResize(){if(!assistantResizeSession)return;const session=assistantResizeSession;assistantResizeSession=null;document.body.classList.remove('assistant-resizing');if(session.handle.hasPointerCapture?.(session.pointerId))session.handle.releasePointerCapture(session.pointerId);if(assistantResizeRenderPending){assistantResizeRenderPending=false;renderAssistantWidget();}}
document.addEventListener('pointerdown',e=>{const handle=e.target.closest('[data-assistant-edge]');if(!handle||e.button!==0||assistantResizeSession)return;e.preventDefault();const start=assistantBoundFrame(assistantWindowFrame());assistantResizeSession={handle,pointerId:e.pointerId,x:e.clientX,y:e.clientY,edge:handle.dataset.assistantEdge,start,mode:assistantWidgetExpanded?'expanded':'compact',reading:captureAssistantReading()};assistantManualFrames[assistantResizeSession.mode]=start;applyAssistantManualFrame();handle.setPointerCapture(e.pointerId);document.body.classList.add('assistant-resizing');});
document.addEventListener('pointermove',e=>{const s=assistantResizeSession;if(!s||e.pointerId!==s.pointerId)return;e.preventDefault();assistantManualFrames[s.mode]=assistantResizeFrame(s.start,s.edge,e.clientX-s.x,e.clientY-s.y);applyAssistantManualFrame();restoreAssistantReading(s.reading);});
for(const event of ['pointerup','pointercancel','lostpointercapture'])document.addEventListener(event,e=>{if(assistantResizeSession?.pointerId===e.pointerId)finishAssistantResize();});
document.addEventListener('keydown',e=>{const handle=e.target.closest('[data-assistant-edge]');if(!handle||!['ArrowLeft','ArrowRight','ArrowUp','ArrowDown'].includes(e.key))return;e.preventDefault();const step=e.shiftKey?32:8,dx=e.key==='ArrowRight'?step:e.key==='ArrowLeft'?-step:0,dy=e.key==='ArrowDown'?step:e.key==='ArrowUp'?-step:0,mode=assistantWidgetExpanded?'expanded':'compact',reading=captureAssistantReading();assistantManualFrames[mode]=assistantResizeFrame(assistantWindowFrame(),handle.dataset.assistantEdge,dx,dy);applyAssistantManualFrame();restoreAssistantReading(reading);});
window.addEventListener('resize',()=>{if(assistantResizeSession)finishAssistantResize();applyAssistantManualFrame();});
