// Connection management is an isolated, in-memory design preview. No service calls.
const connectionAccounts=[
 {id:'demo-main',name:'满室服务机器人',company:'满室 · 主运营空间',login:'满室服务号',online:true,groups:[{id:'demo-room-repair',name:'房修工作群',added:'09-01 09:00'},{id:'demo-room-service',name:'客房工作群',added:'09-01 09:00'},{id:'demo-customer',name:'客服工作群',added:'09-01 09:00'}]},
 {id:'demo-backup',name:'夜班服务机器人',company:'满室 · 夜班空间',login:'待登录',online:false,groups:[]}
];
let connectionAccount='all',agentAccountId='demo-main',connectionSequence=3,ownerPreview=false,credentialConfigured=true;
let messageQuery='',messageDirection='all',messageType='all',messageStatus='all',messagePage=1,messageAuto=false,messageTimer=null,messageUpdated='10:40:00';
const connectionLogs=[
 ['10:38:00','out','房修工作群','demo-room-repair','卡片','A-1208 空调不制冷，已超过接单时限，请房修组确认在岗人员。','已完成','E174'],
 ['10:24:00','out','房修工作群','demo-room-repair','文本','接单提醒：E174 仍待接单，请确认处理人。','已完成','E174'],
 ['10:08:12','out','房修工作群','demo-room-repair','卡片','新工单 E174 · A-1208 · 报修。空调不制冷，请及时接单。','已完成','E174'],
 ['10:08:00','in','A-1208 住户','demo-guest-1208','文本','房间空调不制冷，麻烦安排检查。','已完成','E174'],
 ['10:05:10','out','客房工作群','demo-room-service','文本','E173 已由陈阿姨接单，正在处理。','已完成','E173'],
 ['10:05:00','in','客房工作群','demo-room-service','文本','接单 E173','已完成','E173'],
 ['09:58:00','in','客服工作群','demo-customer','文本','完成 E172，续租咨询已解答。','等待回调','E172'],
 ['09:55:00','out','房修工作群','demo-room-repair','卡片','C-0302 门锁故障，已安排张师傅处理。','已完成','E171'],
 ['09:50:00','in','B-0716 住户','demo-guest-0716','图片','[图片] 房间需要清洁，附现场照片。','已完成','E170'],
 ['09:48:20','out','房修工作群','demo-room-repair','文本','E169 水龙头持续漏水，已升级至 L2 支援。','发送失败','E169'],
 ['09:48:00','in','B-0603 住户','demo-guest-0603','文本','浴室水龙头一直在漏水。','已完成','E169'],
 ['09:20:00','in','客服工作群','demo-customer','文本','E163 等待网络服务商回电，先挂起跟进。','已完成','E163']
].map((r,i)=>({id:`demo-msg-${String(i+1).padStart(3,'0')}`,account:'demo-main',time:r[0],direction:r[1],contact:r[2],chat:r[3],type:r[4],content:r[5],status:r[6],ticket:r[7]}));
function connectionCurrent(){return connectionAccounts.find(a=>a.id===agentAccountId)||connectionAccounts[0];}
function connectionOptions(all=true){return `${all?'<option value="all">全部实例</option>':''}${connectionAccounts.map(a=>`<option value="${a.id}" ${connectionAccount===a.id?'selected':''}>${esc(a.name)}</option>`).join('')}`;}
function connectionAudit(text,actor='丁总'){audit.unshift(['本次预览',actor,text,'演示变更']);}
function connectionRail(items){return `<div class="connection-kpis">${items.map(([label,value,note])=>`<div><span>${label}</span><strong>${value}</strong><small>${note}</small></div>`).join('')}</div>`;}
function connectionStatus(a){return `<span class="status ${a.online?'blue':'muted'}">${icon(a.online?'check':'pause')}${a.online?'在线':'未连接'}</span>`;}
function accountsPage(){const rows=connectionAccounts.filter(a=>connectionAccount==='all'||a.id===connectionAccount);return heading('企微账号','统一管理服务账号，让消息、Agent 与工单在同一处协作。',`<button class="button" data-connection="credentials">${icon('settings')}连接设置</button><button class="button primary" data-connection="add">${icon('plus')}添加企微账号</button>`)+connectionRail([['已接入实例',connectionAccounts.length,'含待连接实例'],['在线实例',connectionAccounts.filter(a=>a.online).length,'当前预览状态'],['连接来源','QiWe','企业微信消息通道'],['运行模式','演示','尚未接入实时服务']])+`<section class="panel connection-panel"><div class="config-title"><div><h2>账号实例</h2><p>每个实例独立管理推送范围与消息记录。</p></div><label class="connection-inline">实例<select data-connection-account aria-label="筛选账号实例">${connectionOptions()}</select></label></div><div class="account-list">${rows.map(a=>`<article class="account-row"><div class="account-identity"><img src="assets/beemax-logo-mark.svg" alt=""><div><h3>${esc(a.name)}</h3><small>${esc(a.company)}</small><div>${connectionStatus(a)} <span class="subtext">${a.online?'QiWe 已连接 · 示例':'等待完成登录'}</span></div></div></div><div class="account-fact"><small>登录账号</small><strong>${esc(a.login)}</strong><small>Agent · ${a.online?'自动接管（演示）':'待连接'}</small></div><div class="account-fact"><small>主动推送范围</small><strong>${a.groups.length} 个授权群</strong><button class="text-link" data-connection-logs="${a.id}">查看消息日志 ${icon('arrow')}</button></div><div class="connection-actions"><button class="button" data-agent="${a.id}">Agent 详情 ${icon('arrow')}</button><button class="text-link" data-manage-account="${a.id}">管理实例</button></div></article>`).join('')}</div></section><div class="connection-note">${icon('help')}账号连接状态、推送权限与工单处理状态分别展示，便于定位问题。</div>`;}
function filteredConnectionLogs(){const q=messageQuery.trim().toLowerCase();return connectionLogs.filter(m=>(connectionAccount==='all'||m.account===connectionAccount)&&(messageDirection==='all'||m.direction===messageDirection)&&(messageType==='all'||m.type===messageType)&&(messageStatus==='all'||m.status===messageStatus)&&(!q||[m.content,m.contact,m.chat,m.id,m.ticket].some(v=>v.toLowerCase().includes(q))));}
function messageLedger(){const rows=filteredConnectionLogs(),pages=Math.max(1,Math.ceil(rows.length/6));messagePage=Math.min(messagePage,pages);return `<div class="connection-ledger-meta"><span>筛选结果 ${rows.length} 条 · 演示消息</span><span>更新于 <time data-message-updated>${messageUpdated}</time></span></div><div class="table-box"><table class="message-table"><thead><tr><th>时间 / 实例</th><th>方向 / 会话</th><th>消息内容</th><th>状态</th><th>操作</th></tr></thead><tbody>${rows.slice((messagePage-1)*6,messagePage*6).map(m=>`<tr><td><strong>${m.time}</strong><small>09-06 · ${esc(connectionAccounts.find(a=>a.id===m.account).name)}</small></td><td><span class="status ${m.direction==='in'?'muted':'blue'}">${m.direction==='in'?'↙ 入站':'↗ 出站'}</span><small>${esc(m.contact)}</small><small>${m.chat.includes('guest')?'单聊':'群聊'}</small></td><td><div class="message-preview"><span class="status muted">${m.type}</span><p>${esc(m.content)}</p></div><button class="text-link" data-ticket="${m.ticket}">关联工单 ${m.ticket} ${icon('arrow')}</button></td><td><span class="status ${m.status==='已完成'?'blue':'muted'}">${m.status==='发送失败'?'! ':m.status==='等待回调'?'◷ ':''}${m.status}</span></td><td><button class="text-link" data-message-detail="${m.id}">详情</button></td></tr>`).join('')||'<tr><td colspan="5"><div class="connection-empty">没有匹配的消息<p>试试其他关键词，或重置筛选条件。</p><button class="button" data-connection="reset-filters">重置筛选</button></div></td></tr>'}</tbody></table></div><div class="connection-pagination"><span>第 ${messagePage} / ${pages} 页 · 每页 6 条</span><button class="button" data-message-page="-1" ${messagePage===1?'disabled':''}>上一页</button><button class="button" data-message-page="1" ${messagePage===pages?'disabled':''}>下一页</button></div>`;}
function messagesPage(){const rows=connectionLogs.filter(m=>connectionAccount==='all'||m.account===connectionAccount);return heading('消息日志','追溯每一条消息，从会话原文找到工单与处理结果。',`<label class="connection-auto"><input type="checkbox" data-message-auto ${messageAuto?'checked':''}>每 15 秒刷新演示视图</label><button class="button" data-connection="refresh">${icon('refresh')}刷新</button>`)+connectionRail([['当前实例日志',rows.length,'全部演示记录'],['入站消息',rows.filter(m=>m.direction==='in').length,'来自住户与工作群'],['出站消息',rows.filter(m=>m.direction==='out').length,'Agent 回复与通知'],['待关注',rows.filter(m=>m.status!=='已完成').length,'等待回调 / 发送失败']])+`<div class="connection-filters"><label class="connection-search">${icon('search')}<input id="message-search" aria-label="搜索消息" placeholder="搜索消息、联系人、会话 ID 或工单" value="${esc(messageQuery)}"></label><select data-connection-account aria-label="日志实例">${connectionOptions()}</select><select data-message-filter="direction" aria-label="消息方向">${[['all','全部方向'],['in','入站'],['out','出站']].map(([v,t])=>`<option value="${v}" ${v===messageDirection?'selected':''}>${t}</option>`).join('')}</select><select data-message-filter="type" aria-label="消息类型">${['all','文本','卡片','图片'].map(v=>`<option value="${v}" ${v===messageType?'selected':''}>${v==='all'?'全部类型':v}</option>`).join('')}</select><select data-message-filter="status" aria-label="消息状态">${['all','已完成','等待回调','发送失败'].map(v=>`<option value="${v}" ${v===messageStatus?'selected':''}>${v==='all'?'全部状态':v}</option>`).join('')}</select></div><section class="panel" id="message-ledger">${messageLedger()}</section><div class="connection-note">${icon('help')}日志状态表示消息通道结果；工单是否闭环请查看关联工单。</div>`;}
function agentPage(){const a=connectionCurrent();return `<a class="text-link connection-back" href="#accounts">← 返回企微账号</a>`+heading('Agent 详情','管理当前账号的主动推送范围。',`<span class="status blue">${icon('check')}仅允许已授权群</span>`)+`<div class="agent-identity"><div class="account-identity"><img src="assets/beemax-logo-mark.svg" alt=""><div><h3>${esc(a.name)}</h3><small>实例 ID：${a.id}</small></div></div>${connectionStatus(a)}<button class="text-link" data-connection-logs="${a.id}">查看消息日志 ${icon('arrow')}</button></div><section class="panel"><div class="config-title"><div><h2>添加主动推送群</h2><p>填写会话 ID，支持长、短字符串；群名称用于识别。</p></div><span class="status muted">${a.groups.length} 个已授权</span></div><form id="whitelist-form" class="whitelist-form"><label>会话 ID（chat_id）<input name="chat" required maxlength="128" placeholder="例如 demo-service-group" autocomplete="off"></label><label>群名称（可选）<input name="name" maxlength="40" placeholder="例如 客服工作群"></label><button class="button primary" type="submit">${icon('plus')}加入白名单</button><p id="whitelist-error" role="alert"></p></form></section><section class="panel authorized-panel"><div class="config-title"><div><h2>已授权群</h2><p>该名单只控制主动推送；人员接单权限在配置管理中设置。</p></div><button class="text-link" data-connection="access">人员权限 ${icon('arrow')}</button></div>${a.groups.map(g=>`<div class="authorized-row"><span class="group-medallion">${icon('chat')}</span><div><strong>${esc(g.name||'未命名群')}</strong><code>${esc(g.id)}</code><small>加入于 ${g.added} · 演示</small></div><button class="icon-button" data-remove-group="${esc(g.id)}" aria-label="移除${esc(g.name||g.id)}">${icon('close')}</button></div>`).join('')||'<div class="connection-empty">尚未授权任何群<p>添加后，这里会显示允许主动推送的范围。</p></div>'}</section>`;}
function connectionSettings(){return `<div class="config-title"><div><h2>QiWe 连接凭据</h2><p>消息接口与 Manager 控制台配置，统一服务于企微账号。</p></div><span class="status ${credentialConfigured?'blue':'muted'}">${credentialConfigured?'已配置 · 示例':'待配置'}</span></div><div class="credential-scope"><div>${icon('settings')}<strong>${ownerPreview?'owner 视图 · 仅设计预览':'运营管理员 · 只读'}</strong><p>${ownerPreview?'此切换仅用于查看表单交互，不代表真实账号权限。请使用示例值。':'连接凭据由 owner 管理；运营管理员可以查看配置状态。'}</p></div><button class="button" data-connection="owner">${ownerPreview?'返回管理员视图':'预览 owner 视图'}</button></div>${ownerPreview?`<form id="credential-form" class="credential-form" autocomplete="off"><label>接口 Token<div class="secret-input"><input name="token" type="password" maxlength="200" placeholder="输入示例 Token 以更新" autocomplete="new-password"><button type="button" class="text-link" data-secret="token" aria-label="显示 Token">显示</button></div><small>QiWe 消息接口 X-QIWE-TOKEN · 留空保留现有配置</small></label><label>Manager 账号<input name="account" maxlength="80" placeholder="输入示例管理账号以更新" autocomplete="off"></label><label>Manager 密码<div class="secret-input"><input name="password" type="password" maxlength="200" placeholder="输入示例密码以更新" autocomplete="new-password"><button type="button" class="text-link" data-secret="password" aria-label="显示密码">显示</button></div></label><div class="credential-footer"><span>仅演示保存反馈，不保存或发送输入的凭据。</span><button class="button" type="reset">重置输入</button><button class="button primary" type="submit">保存配置（演示）</button></div></form>`:`<div class="credential-readonly"><div><span>消息接口 Token</span><strong>•••••••• · 已配置示例</strong></div><div><span>Manager 账号</span><strong>demo-****</strong></div><div><span>Manager 密码</span><strong>•••••••• · 已配置示例</strong></div></div>`}<div class="panel-footer"><button class="text-link" data-connection="accounts">管理企微账号 ${icon('arrow')}</button> <span>账号登录状态请在企微账号页面查看。</span></div>`;}
function connectionPermissions(){return `<div class="config-title"><div><h2>群与人员权限</h2><p>主动推送按账号授权，人员操作按业务角色管理。</p></div><button class="button" data-action="access">新增人员</button></div>${connectionAccounts.map(a=>`<div class="config-row"><div><h3>${esc(a.name)}</h3><p>主动推送白名单 · ${a.groups.length} 个已授权群</p></div><button class="button" data-agent="${a.id}">管理授权群 ${icon('arrow')}</button></div>`).join('')}<div class="config-row"><div><h3>王师傅 · 一线人员</h3><p>房修组 · 本组接单、完成</p></div><span class="status muted">已启用</span></div>`;}
function connectionNavigate(route){if(location.hash===`#${route}`)render();else location.hash=route;}
function updateMessageLedger(){const host=document.getElementById('message-ledger');if(host)host.innerHTML=messageLedger();}
function refreshConnectionMessages(){messageUpdated=new Date().toLocaleTimeString('zh-CN',{hour12:false});document.querySelectorAll('[data-message-updated]').forEach(el=>el.textContent=messageUpdated);}
function connectionTimerSync(){clearInterval(messageTimer);messageTimer=null;if(page==='messages'&&messageAuto)messageTimer=setInterval(refreshConnectionMessages,15000);}
function editConnectionAccount(id){const a=connectionAccounts.find(a=>a.id===id);modal(a?'管理实例':'添加企微账号',`<p>设置实例身份，连接状态仅在本次设计预览中变化。</p><label>实例名称<input id="connection-name" maxlength="40" value="${esc(a?.name||'')}" placeholder="例如 满室服务机器人"></label><label>所属空间<input id="connection-company" maxlength="60" value="${esc(a?.company||'满室 · 运营空间')}"></label>${a?`<label>演示连接状态<select id="connection-state"><option value="online" ${a.online?'selected':''}>在线 · 模拟已登录</option><option value="offline" ${a.online?'':'selected'}>未连接</option></select></label>`:'<div class="note-band">添加后进入待连接状态；正式版在管理实例中完成企微登录。</div>'}`,'保存实例（演示）',m=>{const name=m.querySelector('#connection-name').value.trim(),company=m.querySelector('#connection-company').value.trim();if(!name||!company){toast('请填写实例名称和所属空间');return;}if(a){a.name=name;a.company=company;a.online=m.querySelector('#connection-state').value==='online';a.login=a.online?name:'待登录';}else{connectionAccounts.push({id:`demo-instance-${connectionSequence++}`,name,company,login:'待登录',online:false,groups:[]});connectionAccount='all';}connectionAudit(`${a?'更新':'添加'}企微实例：${name}`);m.close();render();toast('实例已更新，仅在本次预览中生效');});}
document.addEventListener('click',e=>{const b=e.target.closest('button,a');if(!b)return;const act=b.dataset.connection;
 if(act==='credentials'||act==='access'){configTab=act==='credentials'?'connection':'access';connectionNavigate('settings');}
 if(act==='accounts')connectionNavigate('accounts');
 if(act==='add')editConnectionAccount();
 if(act==='owner'){ownerPreview=!ownerPreview;render();}
 if(act==='refresh'){refreshConnectionMessages();toast('已刷新演示视图，没有拉取真实消息');}
 if(act==='reset-filters'){connectionAccount='all';messageQuery='';messageDirection=messageType=messageStatus='all';messagePage=1;render();}
 if(b.dataset.manageAccount)editConnectionAccount(b.dataset.manageAccount);
 if(b.dataset.agent){agentAccountId=b.dataset.agent;connectionNavigate('agent');}
 if(b.dataset.connectionLogs){connectionAccount=b.dataset.connectionLogs;messagePage=1;messageQuery='';messageDirection=messageType=messageStatus='all';connectionNavigate('messages');}
 if(b.dataset.messagePage){messagePage+=Number(b.dataset.messagePage);updateMessageLedger();}
 if(b.dataset.messageDetail){const m=connectionLogs.find(x=>x.id===b.dataset.messageDetail);modal('消息详情',`<div class="modal-summary">消息 ID：${m.id}<br>实例：${esc(connectionAccounts.find(a=>a.id===m.account).name)}<br>会话：${esc(m.contact)}<br>chat_id：${m.chat}<br>时间：09-06 ${m.time}<br>方向：${m.direction==='in'?'入站':'出站'} · ${m.type} · ${m.status}</div><p>${esc(m.content)}</p>${m.direction==='out'&&connectionLogs.some(x=>x.ticket===m.ticket&&x.direction==='in')?`<div class="quote"><small>关联入站消息 · ${esc(connectionLogs.find(x=>x.ticket===m.ticket&&x.direction==='in').contact)}</small><p>${esc(connectionLogs.find(x=>x.ticket===m.ticket&&x.direction==='in').content)}</p></div>`:''}${m.status==='发送失败'?'<div class="note-band">演示失败原因：消息通道连接中断。请检查账号连接状态。</div>':''}${m.status==='等待回调'?'<div class="note-band">尚未收到通道确认，不能据此判断工单状态。</div>':''}`,'查看关联工单 '+m.ticket,d=>{d.close();openTicket(m.ticket);});}
 if(b.dataset.removeGroup){const a=connectionCurrent(),g=a.groups.find(g=>g.id===b.dataset.removeGroup);modal('移除主动推送授权',`<p>确认从 ${esc(a.name)} 的白名单中移除「${esc(g.name||g.id)}」？</p><div class="note-band">正式版中，该 Agent 将不能向此群主动推送；已有工单和历史消息仍保留。</div>`,'确认移除（演示）',m=>{a.groups=a.groups.filter(x=>x!==g);connectionAudit(`${a.name} 移除推送群：${g.name||g.id}`);m.close();render();toast('已移除演示授权');});}
 if(b.dataset.secret){const input=document.querySelector(`#credential-form [name="${b.dataset.secret}"]`);input.type=input.type==='password'?'text':'password';b.textContent=input.type==='password'?'显示':'隐藏';b.setAttribute('aria-label',`${b.textContent}${b.dataset.secret==='token'?' Token':'密码'}`);}
});
document.addEventListener('change',e=>{if(e.target.matches('[data-connection-account]')){connectionAccount=e.target.value;messagePage=1;render();}if(e.target.dataset.messageFilter){const value=e.target.value;({direction:()=>messageDirection=value,type:()=>messageType=value,status:()=>messageStatus=value})[e.target.dataset.messageFilter]();messagePage=1;updateMessageLedger();}if(e.target.matches('[data-message-auto]')){messageAuto=e.target.checked;connectionTimerSync();}});
document.addEventListener('input',e=>{if(e.target.id==='message-search'){messageQuery=e.target.value;messagePage=1;updateMessageLedger();}});
document.addEventListener('submit',e=>{if(e.target.id==='whitelist-form'){e.preventDefault();const a=connectionCurrent(),data=new FormData(e.target),id=data.get('chat').trim(),name=data.get('name').trim(),error=document.getElementById('whitelist-error');if(!/^[a-zA-Z0-9_\-:]{1,128}$/.test(id)){error.textContent='会话 ID 请使用字母、数字、下划线、短横线或冒号。';return;}if(a.groups.some(g=>g.id===id)){error.textContent='该会话已在当前账号的白名单中。';return;}modal('确认添加主动推送群',`<p>允许 ${esc(a.name)} 向以下会话主动推送消息？</p><div class="modal-summary">群名称：${esc(name||'未命名群')}<br>会话 ID：${esc(id)}</div><p>本次仅更新演示白名单，并记录配置变更。</p>`,'确认授权（演示）',m=>{a.groups.push({id,name,added:'本次预览'});connectionAudit(`${a.name} 添加推送群：${name||id}`);m.close();render();toast('已加入当前实例白名单（演示）');});}
 if(e.target.id==='credential-form'){e.preventDefault();if(!ownerPreview)return;const form=e.target;if(!Array.from(form.querySelectorAll('input')).some(i=>i.value.trim())){toast('请先填写需要更新的示例配置');return;}form.reset();credentialConfigured=true;connectionAudit('更新 QiWe 凭据配置（未记录输入内容）','owner（设计预览）');render();toast('已展示保存结果，输入的凭据未保存');}});
