// Design-only report cycles and follow-up state; no background jobs are registered.
let reportCycle='daily',reportArchive='latest';
const analysisSchedules={daily:{name:'日报',cadence:'每天 08:30',next:'09-07 08:30',focus:'昨日异常与今日待办',enabled:true},weekly:{name:'周报',cadence:'每周一 08:30',next:'09-07 08:30',focus:'近 7 天趋势与分工',enabled:true},half:{name:'半月报',cadence:'每月 1、16 日 08:30',next:'09-16 08:30',focus:'半月效率与建议复盘',enabled:true},monthly:{name:'月报',cadence:'每月 1 日 08:30',next:'10-01 08:30',focus:'月度资源与服务改善',enabled:true}};
const recommendationTracking={};
const autoReports={
 daily:{title:'9月5日 · 每日运营分析',range:'2026.09.05 00:00 — 23:59',source:'自动生成示例 · 09-06 08:30',coverage:'完整日数据',description:'昨日新建比闭环多 5 单。今日优先消化已有积压，并明确未闭环工单的下一次跟进时间。',metrics:[['昨日新建','20','单'],['昨日闭环','15','单'],['净增积压','+5','单']],advice:[{id:'daily-backlog',dimension:'流程 / 积压',title:'为未闭环工单安排一次晨间回顾',evidence:'昨日新建 20 单、闭环 15 单，净增积压 5 单；仅一天的数据尚不足以判断积压是否持续恶化。',action:'由各组长回顾未闭环单，确认负责人、阻塞原因与下次跟进时间。先处理无人接单和到期挂起。',review:'次日日报比较净增积压，并检查本批工单的闭环进度。',value:'+5 单',label:'昨日净增积压',destination:'tickets',cta:'查看工单'}]},
 weekly:{title:'8月31日—9月6日 · 周度运营分析',range:'2026.08.31 — 09.06 10:40',source:'提前分析示例 · 本周尚未结束',coverage:'进行中 · 非完整周',description:'新单持续高于闭环，近 7 天积压净增 19 单。优先看消化能力，再结合人员可用工时调整分配。',metrics:[['期间新建','134','单'],['期间闭环','115','单'],['净增积压','+19','单']],advice:[{id:'weekly-capacity',dimension:'流程 / 消化能力',title:'设置一周积压消化安排，避免只追当天新单',evidence:'近 7 天新建 134 单、闭环 115 单，净增 19 单。当前待闭环 37 单，其中挂起 6 单、升级 3 单。',action:'每组每日回顾长期未闭环单，把等待配件、等待住户确认和实际处理分开，并为每单指定下次动作。',review:'下周比较期初和期末积压，同时查看同一批工单的闭环情况。',value:'+19 单',label:'近 7 天净增积压',destination:'trends',cta:'查看趋势依据'},{id:'weekly-roster',dimension:'人员 / 分工',title:'先核实可用工时，再调整房修组支援',evidence:'今日房修组接单 11 单，王师傅接单 8 单、张师傅 3 单；当前待办分别为 5 单和 1 单。这是当日信号，尚不能推断全周分工。',action:'由运营确认两人值班时长、任务难度与可用工时，再决定是否增加二档支援。',review:'下一期比较同等在岗时长下的响应与待办变化，不仅比较接单数。',value:'8 : 3',label:'今日房修组接单分配',destination:'staff',cta:'查看人员负载'}]},
 half:{title:'9月上半月 · 运营复盘',range:'2026.09.01 — 09.06 10:40',source:'阶段预览 · 09-16 生成完整半月报',coverage:'仅覆盖 6 / 15 天',description:'本期尚未结束。先汇总已有数据，完整半月报会回顾高频问题、负载变化及已采纳建议的效果。',metrics:[['已记录新单','118','单'],['已记录闭环','101','单'],['净增积压','+17','单']],advice:[]},
 monthly:{title:'9月 · 月度运营分析',range:'2026.09.01 — 09.06 10:40',source:'阶段预览 · 10-01 生成完整月报',coverage:'仅覆盖 6 / 30 天',description:'月报重点回答资源是否合理、重复问题是否减少、服务效率是否改善。本期及上期数据不完整，暂不生成月度调配建议。',metrics:[['已记录新单','118','单'],['已记录闭环','101','单'],['净增积压','+17','单']],advice:[]}
};
const previousDaily={title:'9月4日 · 每日运营分析',range:'2026.09.04 00:00 — 23:59',source:'历史报告示例 · 09-05 08:30',coverage:'完整日数据',description:'当日新建与闭环均为 20 单，积压无净增长。仅凭总量未发现需要新增行动的信号，继续跟进已有工单。',metrics:[['当日新建','20','单'],['当日闭环','20','单'],['净增积压','0','单']],advice:[]};
function insights(){const s=analysisSchedules[reportCycle],r=reportArchive==='adhoc'?adHocReport:reportArchive==='previous'?previousDaily:reportForPlan(reportCycle);const tracked=Object.values(recommendationTracking);return heading('AI智能分析','由 AI 智能体或大模型结合工单、事件记录与历史建议，分析运营问题并提出行动建议。',`<button class="button" data-auto-action="schedule">${icon('settings')}自动分析设置</button><button class="button primary" data-auto-action="generate">${icon('spark')}立即分析</button>`)+`
<div class="ai-method"><div><span class="medallion">${icon('spark')}</span><strong>AI 运营分析助手</strong><span class="status muted">模型待接入 · 设计预览</span></div><p><span>读取工单与处理记录</span>${icon('arrow')}<span>结合历史建议，分析问题与可能原因</span>${icon('arrow')}<span>给出有依据的建议，持续复盘</span></p></div>
<section class="automation-rail" aria-label="自动分析计划"><div class="automation-heading"><span class="medallion">${icon('clock')}</span><div><strong>AI 周期分析</strong><p>${Object.values(analysisSchedules).filter(v=>v.enabled).length} 个周期计划开启 · 报告保存在工作台</p></div><button class="text-link" data-auto-action="schedule">${icon('plus')}自定义计划</button></div><div class="schedule-grid">${Object.entries(analysisSchedules).map(([key,v])=>`<button data-report-cycle="${key}" class="schedule-item ${reportCycle===key?'active':''}" aria-pressed="${reportCycle===key}"><span class="schedule-name">${esc(v.name)}<small>${v.enabled?'计划开启':'已暂停'}</small></span><strong>${esc(v.cadence)}</strong><span>${esc(v.focus)}</span></button>`).join('')}</div></section>
<div class="report-toolbar"><div class="pill-tabs" aria-label="分析报告周期">${Object.entries(analysisSchedules).map(([key,v])=>`<button data-report-cycle="${key}" class="${reportCycle===key?'active':''}" aria-pressed="${reportCycle===key}">${esc(v.name)}</button>`).join('')}</div><button class="button" data-auto-action="custom-range">${icon('calendar')}自定义日期</button><span>${icon('calendar')} ${reportArchive==='adhoc'?'手动分析 · 不改变自动计划':`下次计划：${s.enabled?s.next+' · UTC+8':'已暂停'}`}</span></div>
<div class="report-layout"><section class="panel report-main"><div class="panel-heading"><div><div class="eyebrow">${reportArchive==='adhoc'?'CUSTOM RANGE':reportArchive==='previous'?'HISTORY':'LATEST REPORT'} / ${reportArchive==='adhoc'?'手动分析':esc(s.name)}</div><h2>${r.title}</h2><div class="subtext">${r.range}</div></div><span class="status ${r.advice.length?'blue':'muted'}">${r.coverage}</span></div><div class="report-summary"><p>${r.description}</p><div class="report-metrics">${r.metrics.map(([n,v,u])=>`<div><span>${n}</span><strong>${v}<small>${u}</small></strong></div>`).join('')}</div></div><div class="recommendation-heading"><h3>运营建议 <span class="count-chip">${r.advice.length}</span></h3><span>依据 → 行动 → 下期复盘</span></div>${r.advice.length?`<div class="analysis-list">${r.advice.map((a,i)=>`<article class="analysis-item recommendation"><div class="analysis-number">0${i+1}</div><div><div class="eyebrow">${a.dimension}</div><h3>${a.title}</h3><p><b>数据依据</b>　${a.evidence}</p><p><b>建议行动</b>　${a.action}</p><p class="review-line"><b>下期复盘</b>　${a.review}</p><div class="recommendation-actions"><a class="text-link" href="#${a.destination}">${a.cta} ${icon('arrow')}</a><button class="button ${recommendationTracking[a.id]?'':'primary'}" data-track-advice="${a.id}">${recommendationTracking[a.id]?'查看跟进':'纳入跟进'}</button></div></div></article>`).join('')}</div>`:`<div class="report-empty"><span class="medallion">${icon(reportArchive==='previous'?'check':'clock')}</span><h3>${reportArchive==='previous'?'本期暂无新增建议':esc(r.emptyTitle||'数据不足，先观察，不下定论')}</h3><p>${reportArchive==='previous'?'继续跟进已有事项。没有明显运营信号时，不为凑数量生成建议。':esc(r.emptyReason||'当前周期与对照数据不完整。完整周期结束后，再判断是否需要调整排班、资源或服务规则。')}</p></div>`}<div class="panel-footer"><span>${r.source}</span><span>所有结论均为演示</span></div></section>
<aside class="report-aside"><section class="panel"><div class="panel-heading"><h2>历史报告</h2><span class="subtext">示例</span></div><div class="report-history">${adHocReport?`<button data-view-adhoc class="${reportArchive==='adhoc'?'active':''}"><span>${icon('calendar')}<strong>自定义区间分析</strong></span><small>${adHocReport.range}</small></button>`:''}${[['daily','latest','9月5日 · 日报','09-06 08:30 · 自动生成'],['daily','previous','9月4日 · 日报','09-05 08:30 · 暂无新建议'],['weekly','latest','本周 · 阶段分析','截至 09-06 10:40']].map(([cycle,archive,t,p])=>`<button data-report-history="${cycle}:${archive}" class="${reportCycle===cycle&&reportArchive===archive?'active':''}"><span>${icon('ticket')}<strong>${t}</strong></span><small>${p}</small></button>`).join('')}</div><div class="panel-footer">各周期及自定义区间报告分别归档</div></section><section class="panel"><div class="panel-heading"><h2>建议跟进</h2><span class="count-chip">${tracked.length}</span></div><div class="followup-content">${tracked.length?tracked.map(a=>`<button class="followup-item" data-track-advice="${a.id}"><strong>${esc(a.title)}</strong><span>${esc(a.owner)} · ${esc(a.state)}</span><small>计划复盘 ${esc(a.date)} ${icon('arrow')}</small></button>`).join(''):`<span class="medallion">${icon('check')}</span><p>采纳建议后，指定负责人和复盘时间。下一期继续回看同一项建议的效果。</p>`}</div></section><div class="report-footnote">${icon('help')}<p>自动分析负责给出建议。排班、派单及规则调整仍由运营确认后执行。<br><br>默认站内查看；私信推送可在后续设置中启用。</p></div></aside></div>`;}
function followRecommendation(id){const advice=Object.values(autoReports).flatMap(r=>r.advice).find(a=>a.id===id);const tracked=recommendationTracking[id];modal(tracked?'建议跟进与复盘':'将建议纳入跟进',`<div class="modal-summary">${advice.title}</div><label>负责人<input id="follow-owner" value="${esc(tracked?.owner||'丁总')}" placeholder="填写负责人员"></label><label>计划复盘日期<input id="follow-date" type="date" value="${esc(tracked?.date||'2026-09-07')}"></label>${tracked?`<label>跟进状态<select id="follow-state">${['待执行','执行中','待观察','已复盘'].map(t=>`<option ${tracked.state===t?'selected':''}>${t}</option>`).join('')}</select></label><label>复盘记录<input id="follow-note" value="${esc(tracked.note||'')}" placeholder="记录结果或仍需观察的原因"></label>`:''}<p>下期分析会回看这项建议的处理记录与相关指标。当前仅保存到浏览器预览，刷新后恢复。</p>`,tracked?'保存跟进（演示）':'确认跟进（演示）',m=>{const owner=m.querySelector('#follow-owner').value.trim(),date=m.querySelector('#follow-date').value;if(!owner||!date){toast('请填写负责人及复盘日期');return;}recommendationTracking[id]={id,title:advice.title,owner,date,state:m.querySelector('#follow-state')?.value||'待执行',note:m.querySelector('#follow-note')?.value||''};m.close();render();toast('已加入预览跟进清单');});}
document.addEventListener('click',e=>{const b=e.target.closest('button');if(!b)return;if(b.dataset.reportCycle){reportCycle=b.dataset.reportCycle;reportArchive='latest';render();}if(b.dataset.reportHistory){[reportCycle,reportArchive]=b.dataset.reportHistory.split(':');render();}if(b.dataset.trackAdvice)followRecommendation(b.dataset.trackAdvice);if(b.dataset.autoAction==='schedule')showAnalysisSchedule();if(b.dataset.autoAction==='generate'){modal('立即分析已有数据',`<p>基于目前已有记录，提前查看${esc(analysisSchedules[reportCycle].name)}。未结束的周期会标注为阶段分析，不冒充完整报告。</p><div class="modal-summary">分析范围：${reportForPlan(reportCycle).range}<br>分析方式：AI 智能体或大模型关联分析<br>输入：工单、完整事件记录、人员负载、历史建议<br>维度：类型、人员、时间、处理流程<br>结果：可核查依据、可能原因、运营建议与复盘指标</div><p>当前演示固定报告内容，未连接模型或后台调度。</p>`,'查看报告示例',m=>{m.close();reportArchive='latest';render();toast('已展示已有数据的分析示例');});}});
