import type {Actor,Command,Workspace,Plan,Conversation} from '../../shared/domain.ts';
import { randomUUID,createHash } from 'node:crypto';
import { AppError,requireValue,text,number } from './errors.ts';
import { Store } from './store.ts';
import { nextRun,validDate } from './dates.ts';
export interface DataProvider {mode:'local'|'mcp'; read(actor:Actor):Promise<Workspace>; command(actor:Actor,command:Command):Promise<{revision:number}>}
// MCP schemas and tool capability mapping will be supplied by the integration owner.
// Never fall back to local writes when the configured upstream is unavailable.
export class PendingMcpProvider implements DataProvider {mode='mcp' as const;async read(_actor:Actor):Promise<Workspace>{throw new AppError(503,'MCP_NOT_CONFIGURED','MCP 接口契约尚未配置，请完成工具映射后启用 MCP 模式。');}async command(_actor:Actor,_command:Command):Promise<{revision:number}>{throw new AppError(503,'MCP_NOT_CONFIGURED','尚未配置 MCP 写工具；未执行任何操作。');}}
export function validatePlan(data:Record<string,unknown>,old?:Plan):Plan{const v={...old,...data},p={id:old?.id||randomUUID(),name:text(v.name,'计划名称',40),enabled:v.enabled===true,frequency:text(v.frequency,'生成频率'),time:text(v.time,'生成时间'),weekday:number(v.weekday,'星期',0,6),monthDay:number(v.monthDay,'日期',1,31),yearMonth:number(v.yearMonth,'月份',1,12),every:number(v.every,'间隔',1,365),unit:text(v.unit,'单位'),anchor:text(v.anchor,'首次日期'),range:text(v.range,'分析范围'),rangeDays:number(v.rangeDays,'回顾天数',1,3660),nextRun:''} as Plan;
 requireValue(['daily','weekly','half','monthly','quarterly','yearly','interval'].includes(p.frequency),'生成频率无效');requireValue(/^([01]\d|2[0-3]):[0-5]\d$/.test(p.time),'时间格式无效');requireValue(['days','weeks','months','years'].includes(p.unit),'间隔单位无效');requireValue(validDate(p.anchor)&&p.anchor>='2000-01-01'&&p.anchor<='2100-12-31','首次日期无效');requireValue(['previousDay','previousWeek','previousHalf','previousMonth','previousQuarter','previousYear','rolling'].includes(p.range),'分析范围无效');p.nextRun=nextRun(p);return p;}
export class LocalProvider implements DataProvider {
 mode='local' as const;
 constructor(public store:Store){}
 async read(actor:Actor){return this.store.read(actor.tenantId);}
 async command(actor:Actor,c:Command){requireValue(actor.role!=='viewer','当前账号只有查看权限',403);requireValue(c&&typeof c.type==='string'&&c.data&&typeof c.data==='object'&&!Array.isArray(c.data),'请求格式无效');text(c.requestId,'请求标识',100);number(c.expectedRevision,'数据版本',1,Number.MAX_SAFE_INTEGER);
 const db=this.store.db,fingerprint=createHash('sha256').update(JSON.stringify(c)).digest('hex');db.exec('BEGIN IMMEDIATE');try {const prior=db.prepare('SELECT fingerprint,result FROM requests WHERE tenant=? AND actor=? AND id=?').get(actor.tenantId,actor.id,c.requestId) as {fingerprint:string;result:string}|undefined;if(prior){requireValue(prior.fingerprint===fingerprint,'请求标识已用于其他操作',409);db.exec('COMMIT');return JSON.parse(prior.result) as {revision:number};}
 const w=this.store.read(actor.tenantId);if(w.revision!==c.expectedRevision)throw new AppError(409,'REVISION_CONFLICT','数据已更新，请刷新后核对并重试。');this.apply(w,actor,c);w.revision++;w.audit.unshift({id:randomUUID(),at:new Date().toISOString(),actor:actor.name,action:c.type,target:String(c.data.id||c.data.accountId||''),detail:c.type==='credentials.save'?'更新连接凭据（内容不记录）':this.auditSummary(w,c)});w.audit=w.audit.slice(0,2000);this.store.save(w);const result={revision:w.revision};db.prepare('INSERT INTO requests VALUES(?,?,?,?,?)').run(actor.tenantId,actor.id,c.requestId,fingerprint,JSON.stringify(result));db.exec('COMMIT');return result;
 }catch(error){db.exec('ROLLBACK');throw error;}}
 private auditSummary(w:Workspace,c:Command){const d=c.data;return c.type==='ticket.action'?`${d.id} · ${d.action}${d.reason?' · '+String(d.reason).slice(0,200):''}`:c.type==='route.save'?`${d.type} → ${w.groups.find(g=>g.id===d.groupId)?.name}`:c.type==='parameters.save'?`升级 ${w.parameters.escalationMinutes} 分钟 / 接单提醒 ${w.parameters.acceptReminderMinutes} 分钟 / 挂起提醒 ${w.parameters.holdReminderMinutes} 分钟`:c.type==='learning.save'?`学习自动应用 ${w.learning.autoApply?'开启':'关闭'} / 灰度 ${w.learning.routingShadow?'开启':'关闭'}`:c.type==='group.add'?`授权群 ${d.name||d.chatId}`:c.type==='plan.save'?`分析计划 ${d.name}`:c.type==='person.save'?`人员 ${d.name}`:c.type==='account.save'?`实例 ${d.name}`:c.type==='advice.update'?`建议状态 → ${d.status}`:'操作成功';}
 private apply(w:Workspace,actor:Actor,c:Command){const d=c.data,now=new Date().toISOString(),group=(id:unknown)=>{requireValue(w.groups.some(g=>g.id===id),'小组不存在');return String(id);},id=typeof d.id==='string'?d.id:'';
 switch(c.type){case'ticket.action':{const t=w.tickets.find(t=>t.id===id);requireValue(t,'工单不存在',404);const action=text(d.action,'操作');requireValue(t.status!=='CLOSED','已闭环工单不能再次操作',409);requireValue(['urge','reassign','hold','resume','complete'].includes(action),'未知操作');if(action==='hold'){requireValue(t.status!=='ON_HOLD','工单已经挂起',409);t.holdReason=text(d.reason,'挂起原因',500);requireValue(typeof d.remindAt==='string'&&Number.isFinite(Date.parse(d.remindAt))&&Date.parse(d.remindAt)>Date.now(),'跟进时间必须晚于当前时间');t.remindAt=new Date(d.remindAt).toISOString();t.status='ON_HOLD';}if(action==='resume'){requireValue(t.status==='ON_HOLD','只能恢复已挂起工单',409);t.status=t.assigneeId?'IN_PROGRESS':'DISPATCHED';delete t.remindAt;delete t.holdReason;}if(action==='reassign'){t.groupId=group(d.groupId);const person=w.people.find(p=>p.id===d.assigneeId&&p.groupId===t.groupId&&p.active);requireValue(!d.assigneeId||person,'处理人不属于所选小组或未在岗');t.assigneeId=person?.id||null;t.status=person?'ACCEPTED':'DISPATCHED';t.acceptedAt=person?now:null;delete t.remindAt;delete t.holdReason;}if(action==='complete'){t.status='CLOSED';t.closedAt=now;delete t.remindAt;}t.version++;t.events.push({at:now,name:({urge:'催办',reassign:'转派',hold:'挂起',resume:'恢复',complete:'完成'})[action]!,detail:action==='hold'?t.holdReason!:action==='reassign'?`转派至 ${w.groups.find(g=>g.id===t.groupId)!.name}`:'本地操作已保存；未发送企微通知',by:actor.name});break;}
 case'route.save':{const row={id:id||randomUUID(),type:text(d.type,'问题类型',40),keywords:text(d.keywords,'关键词',300),groupId:group(d.groupId),source:'人工配置'};if(id){const i=w.routes.findIndex(r=>r.id===id);requireValue(i>=0,'规则不存在',404);w.routes[i]=row;}else w.routes.push(row);break;}
 case'route.delete':requireValue(w.routes.some(r=>r.id===id),'规则不存在',404);w.routes=w.routes.filter(r=>r.id!==id);break;
 case'person.save':{const row={id:id||randomUUID(),name:text(d.name,'人员名称',40),groupId:group(d.groupId),tier:number(d.tier,'档位',1,5),active:d.active===true};if(id){const i=w.people.findIndex(p=>p.id===id);requireValue(i>=0,'人员不存在',404);w.people[i]=row;}else w.people.push(row);break;}
 case'parameters.save':w.parameters={escalationMinutes:number(d.escalationMinutes,'升级间隔',1,1440),acceptReminderMinutes:number(d.acceptReminderMinutes,'接单提醒',1,1440),holdReminderMinutes:number(d.holdReminderMinutes,'挂起提醒',1,1440)};break;
 case'learning.save':requireValue(typeof d.autoApply==='boolean'&&typeof d.routingShadow==='boolean','开关格式错误');w.learning={autoApply:d.autoApply,routingShadow:d.routingShadow};break;
 case'account.save':{const a=w.accounts.find(a=>a.id===id);requireValue(!id||a,'实例不存在',404);if(a){a.name=text(d.name,'实例名称',40);a.company=text(d.company,'所属空间',60);}else w.accounts.push({id:randomUUID(),name:text(d.name,'实例名称',40),company:text(d.company,'所属空间',60),login:'待接入',status:'offline',groups:[]});break;}
 case'group.add':{const a=w.accounts.find(a=>a.id===d.accountId);requireValue(a,'实例不存在',404);const chatId=text(d.chatId,'会话 ID',128);requireValue(/^[a-zA-Z0-9_:\-]+$/.test(chatId),'会话 ID 格式无效');requireValue(!a.groups.some(g=>g.id===chatId),'该会话已授权',409);a.groups.push({id:chatId,name:typeof d.name==='string'?d.name.trim().slice(0,40):'',addedAt:now});break;}
 case'group.remove':{const a=w.accounts.find(a=>a.id===d.accountId);requireValue(a,'实例不存在',404);requireValue(a.groups.some(g=>g.id===d.chatId),'授权群不存在',404);a.groups=a.groups.filter(g=>g.id!==d.chatId);break;}
 case'credentials.save':{requireValue(actor.role==='owner','仅 owner 可以管理连接凭据',403);const values=this.store.getSecret(actor.tenantId);let changed=false;for(const field of ['token','account','password'])if(d[field]!==undefined&&d[field]!==''){values[field]=text(d[field],field,500);changed=true;}requireValue(changed,'请填写要更新的凭据');this.store.setSecret(actor.tenantId,values);w.credentials={configured:!!values.token,accountMask:values.account?values.account.slice(0,2)+'****':'',updatedAt:now};break;}
 case'plan.save':{const old=w.plans.find(p=>p.id===id);requireValue(!id||old,'计划不存在',404);const p=validatePlan(d,old);if(old)w.plans[w.plans.indexOf(old)]=p;else w.plans.push(p);break;}
 case'plan.delete':requireValue(w.plans.some(p=>p.id===id),'计划不存在',404);w.plans=w.plans.filter(p=>p.id!==id);break;
 case'advice.update':{const report=w.reports.find(r=>r.id===d.reportId),advice=report?.advice.find(a=>a.id===id);requireValue(advice,'建议不存在',404);requireValue(['new','following','done'].includes(String(d.status)),'建议状态无效');if(d.status==='following'){requireValue(w.people.some(p=>p.id===d.ownerId),'请选择跟进负责人');requireValue(validDate(d.reviewAt),'请选择有效复盘日期');advice.ownerId=String(d.ownerId);advice.reviewAt=String(d.reviewAt);}advice.status=d.status as typeof advice.status;break;}
 default:throw new AppError(400,'UNKNOWN_COMMAND','不支持的操作');}
 }
 saveConversation(actor:Actor,conversation:Conversation){const w=this.store.read(actor.tenantId),all=w.conversations[actor.id]||[],i=all.findIndex(c=>c.id===conversation.id);if(i<0)all.unshift(conversation);else all[i]=conversation;w.conversations[actor.id]=all.slice(0,30);this.store.save(w);}
}
